const regions = [
  { name: "NCR", long: "National Capital Region", key: "NCR" },
  { name: "CAR", long: "Cordillera Admininstrative Region", key: "CAR" },
  { name: "Region I", long: "Ilocos Region", key: "I" },
  { name: "Region II", long: "Cagayan Valley", key: "II" },
  { name: "Region III", long: "Central Luzon", key: "III" },
  { name: "Region IV-A", long: "CALABARZON", key: "IV-A" },
  { name: "Region IV-B", long: "MIMAROPA", key: "IV-B" },
  { name: "Region V", long: "Bicol Region", key: "V" },
  { name: "Region VI", long: "Western Visayas", key: "VI" },
  { name: "Region VII", long: "Central Visayas", key: "VII" },
  { name: "Region VIII", long: "Eastern Visayas", key: "VIII" },
  { name: "Region IX", long: "Zamboange Peninsula", key: "IX" },
  { name: "Region X", long: "Northen Mindanao", key: "X" },
  { name: "Region XI", long: "Davao Region", key: "XI" },
  { name: "Region XII", long: "SOCCSKARGEN", key: "XII" },
  { name: "Region XIII", long: "Caraga", key: "XIII" },
  { name: "ARMM", long: "Autonomous Region in Muslim Mindanao", key: "ARMM" },
];
const provinces = [
  { name: "Metro Manila", region: "NCR", key: "MM" },

  { name: "Abra", region: "CAR", key: "ABR" },
  { name: "Apayao", region: "CAR", key: "APA" },
  { name: "Benguet", region: "CAR", key: "BEN" },
  { name: "Ifugao", region: "CAR", key: "IFU" },
  { name: "Kalinga", region: "CAR", key: "KAL" },
  { name: "Mountain Province", region: "CAR", key: "MOU" },

  { name: "Ilocos Norte", region: "I", key: "ILN" },
  { name: "Ilocos Sur", region: "I", key: "ILS" },
  { name: "La Union", region: "I", key: "LUN" },
  { name: "Pangasinan", region: "I", key: "PAN" },

  { name: "Batanes", region: "II", key: "BTN" },
  { name: "Cagayan", region: "II", key: "CAG" },
  { name: "Isabela", region: "II", key: "ISA" },
  { name: "Nueva Vizcaya", region: "II", key: "NUV" },
  { name: "Quirino", region: "II", key: "QUI" },

  { name: "Aurora", region: "III", key: "AUR" },
  { name: "Bataan", region: "III", key: "BAN" },
  { name: "Bulacan", region: "III", key: "BUL" },
  { name: "Nueva Ecija", region: "III", key: "NUE" },
  { name: "Pampanga", region: "III", key: "PAM" },
  { name: "Tarlac", region: "III", key: "TAR" },
  { name: "Zambales", region: "III", key: "ZMB" },

  { name: "Batangas", region: "IV-A", key: "BTG" },
  { name: "Cavite", region: "IV-A", key: "CAV" },
  { name: "Laguna", region: "IV-A", key: "LAG" },
  { name: "Quezon", region: "IV-A", key: "QUE" },
  { name: "Rizal", region: "IV-A", key: "RIZ" },

  { name: "Marinduque", region: "IV-B", key: "MAD" },
  { name: "Occidental Mindoro", region: "IV-B", key: "MDC" },
  { name: "Oriental Mindoro", region: "IV-B", key: "MDR" },
  { name: "Palawan", region: "IV-B", key: "PLW" },
  { name: "Romblon", region: "IV-B", key: "ROM" },

  { name: "Albay", region: "V", key: "ALB" },
  { name: "Camarines Norte", region: "V", key: "CAN" },
  { name: "Camarines Sur", region: "V", key: "CAS" },
  { name: "Catanduanes", region: "V", key: "CAT" },
  { name: "Masbate", region: "V", key: "MAS" },
  { name: "Sorsogon", region: "V", key: "SOR" },

  { name: "Aklan", region: "VI", key: "AKL" },
  { name: "Antique", region: "VI", key: "ANT" },
  { name: "Capiz", region: "VI", key: "CAP" },
  { name: "Guimaras", region: "VI", key: "GUI" },
  { name: "Iloilo", region: "VI", key: "ILI" },
  { name: "Negros Occidental", region: "VI", key: "NEC" },

  { name: "Bohol", region: "VII", key: "BOH" },
  { name: "Cebu", region: "VII", key: "CEB" },
  { name: "Negros Oriental", region: "VII", key: "NER" },
  { name: "Siquijor", region: "VII", key: "SIG" },

  { name: "Biliran", region: "VIII", key: "BIL" },
  { name: "Eastern Samar", region: "VIII", key: "EAS" },
  { name: "Leyte", region: "VIII", key: "LEY" },
  { name: "Northern Samar", region: "VIII", key: "NSA" },
  { name: "Samar", region: "VIII", key: "WSA" },
  { name: "Southern Leyte", region: "VIII", key: "SLE" },

  { name: "Zamboanga del Norte", region: "IX", key: "ZAN" },
  { name: "Zamboanga del Sur", region: "IX", key: "ZAS" },
  { name: "Zamboanga Sibugay", region: "IX", key: "ZSI" },

  { name: "Bukidnon", region: "X", key: "BUK" },
  { name: "Camiguin", region: "X", key: "CAM" },
  { name: "Lanao del Norte", region: "X", key: "LAN" },
  { name: "Misamis Occidental", region: "X", key: "MSC" },
  { name: "Misamis Oriental", region: "X", key: "MSR" },

  { name: "Compostela Valley", region: "XI", key: "COM" },
  { name: "Davao del Norte", region: "XI", key: "DAV" },
  { name: "Davao del Sur", region: "XI", key: "DAS" },
  { name: "Davao Occidental", region: "XI", key: "DAC" },
  { name: "Davao Oriental", region: "XI", key: "DAO" },

  { name: "Cotabato", region: "XII", key: "NCO" },
  { name: "Sarangani", region: "XII", key: "SAR" },
  { name: "South Cotabato", region: "XII", key: "SCO" },
  { name: "Sultan Kudarat", region: "XII", key: "SUK" },

  { name: "Agusan del Norte", region: "XIII", key: "AGN" },
  { name: "Agusan del Sur", region: "XIII", key: "AGS" },
  { name: "Dinagat Islands", region: "XIII", key: "DIN" },
  { name: "Surigao del Norte", region: "XIII", key: "SUN" },
  { name: "Surigao del Sur", region: "XIII", key: "SUR" },

  { name: "Basilan", region: "ARMM", key: "BAS" },
  { name: "Lanao del Sur", region: "ARMM", key: "LAS" },
  { name: "Maguindanao", region: "ARMM", key: "MAG" },
  { name: "Sulu", region: "ARMM", key: "SLU" },
  { name: "Tawi-tawi", region: "ARMM", key: "TAW" },
];
const cities = [
  { name: "Caloocan", province: "MM", city: true, region: "NCR" },
  { name: "Las Piñas", province: "MM", city: true, region: "NCR" },
  { name: "Makati", province: "MM", city: true, region: "NCR" },
  { name: "Malabon", province: "MM", city: true, region: "NCR" },
  { name: "Mandaluyong", province: "MM", city: true, region: "NCR" },
  { name: "Manila", province: "MM", city: true, region: "NCR" },
  { name: "Marikina", province: "MM", city: true, region: "NCR" },
  { name: "Muntinlupa", province: "MM", city: true, region: "NCR" },
  { name: "Navotas", province: "MM", city: true, region: "NCR" },
  { name: "Parañaque", province: "MM", city: true, region: "NCR" },
  { name: "Pasay", province: "MM", city: true, region: "NCR" },
  { name: "Pasig", province: "MM", city: true, region: "NCR" },
  { name: "Pateros", province: "MM", region: "NCR" },
  { name: "Quezon", province: "MM", city: true, region: "NCR" },
  { name: "San Juan", province: "MM", city: true, region: "NCR" },
  { name: "Taguig", province: "MM", city: true, region: "NCR" },
  { name: "Valenzuela", province: "MM", city: true, region: "NCR" },
  { name: "Bangued", province: "ABR", region: "CAR" },
  { name: "Boliney", province: "ABR", region: "CAR" },
  { name: "Bucay", province: "ABR", region: "CAR" },
  { name: "Bucloc", province: "ABR", region: "CAR" },
  { name: "Daguioman", province: "ABR", region: "CAR" },
  { name: "Danglas", province: "ABR", region: "CAR" },
  { name: "Dolores", province: "ABR", region: "CAR" },
  { name: "La Paz", province: "ABR", region: "CAR" },
  { name: "Lacub", province: "ABR", region: "CAR" },
  { name: "Lagangilang", province: "ABR", region: "CAR" },
  { name: "Lagayan", province: "ABR", region: "CAR" },
  { name: "Langiden", province: "ABR", region: "CAR" },
  { name: "Licuan-Baay", province: "ABR", region: "CAR" },
  { name: "Luba", province: "ABR", region: "CAR" },
  { name: "Malibcong", province: "ABR", region: "CAR" },
  { name: "Manabo", province: "ABR", region: "CAR" },
  { name: "Peñarrubia", province: "ABR", region: "CAR" },
  { name: "Pidigan", province: "ABR", region: "CAR" },
  { name: "Pilar", province: "ABR", region: "CAR" },
  { name: "Sallapadan", province: "ABR", region: "CAR" },
  { name: "San Isidro", province: "ABR", region: "CAR" },
  { name: "San Juan", province: "ABR", region: "CAR" },
  { name: "San Quintin", province: "ABR", region: "CAR" },
  { name: "Tayum", province: "ABR", region: "CAR" },
  { name: "Tineg", province: "ABR", region: "CAR" },
  { name: "Tubo", province: "ABR", region: "CAR" },
  { name: "Villaviciosa", province: "ABR", region: "CAR" },
  { name: "Calanasan", province: "APA", region: "CAR" },
  { name: "Conner", province: "APA", region: "CAR" },
  { name: "Flora", province: "APA", region: "CAR" },
  { name: "Kabugao", province: "APA", region: "CAR" },
  { name: "Luna", province: "APA", region: "CAR" },
  { name: "Pudtol", province: "APA", region: "CAR" },
  { name: "Santa Marcela", province: "APA", region: "CAR" },
  { name: "Atok", province: "BEN", region: "CAR" },
  { name: "Baguio", province: "BEN", city: true, region: "CAR" },
  { name: "Bakun", province: "BEN", region: "CAR" },
  { name: "Bokod", province: "BEN", region: "CAR" },
  { name: "Buguias", province: "BEN", region: "CAR" },
  { name: "Itogon", province: "BEN", region: "CAR" },
  { name: "Kabayan", province: "BEN", region: "CAR" },
  { name: "Kapangan", province: "BEN", region: "CAR" },
  { name: "Kibungan", province: "BEN", region: "CAR" },
  { name: "La Trinidad", province: "BEN", region: "CAR" },
  { name: "Mankayan", province: "BEN", region: "CAR" },
  { name: "Sablan", province: "BEN", region: "CAR" },
  { name: "Tuba", province: "BEN", region: "CAR" },
  { name: "Tublay", province: "BEN", region: "CAR" },
  { name: "Aguinaldo", province: "IFU", region: "CAR" },
  { name: "Alfonso Lista", province: "IFU", region: "CAR" },
  { name: "Asipulo", province: "IFU", region: "CAR" },
  { name: "Banaue", province: "IFU", region: "CAR" },
  { name: "Hingyon", province: "IFU", region: "CAR" },
  { name: "Hungduan", province: "IFU", region: "CAR" },
  { name: "Kiangan", province: "IFU", region: "CAR" },
  { name: "Lagawe", province: "IFU", region: "CAR" },
  { name: "Lamut", province: "IFU", region: "CAR" },
  { name: "Mayoyao", province: "IFU", region: "CAR" },
  { name: "Tinoc", province: "IFU", region: "CAR" },
  { name: "Balbalan", province: "KAL", region: "CAR" },
  { name: "Lubuagan", province: "KAL", region: "CAR" },
  { name: "Pasil", province: "KAL", region: "CAR" },
  { name: "Pinukpuk", province: "KAL", region: "CAR" },
  { name: "Rizal", province: "KAL", region: "CAR" },
  { name: "Tabuk", province: "KAL", city: true, region: "CAR" },
  { name: "Tanudan", province: "KAL", region: "CAR" },
  { name: "Tinglayan", province: "KAL", region: "CAR" },
  { name: "Barlig", province: "MOU", region: "CAR" },
  { name: "Bauko", province: "MOU", region: "CAR" },
  { name: "Besao", province: "MOU", region: "CAR" },
  { name: "Bontoc", province: "MOU", region: "CAR" },
  { name: "Natonin", province: "MOU", region: "CAR" },
  { name: "Paracelis", province: "MOU", region: "CAR" },
  { name: "Sabangan", province: "MOU", region: "CAR" },
  { name: "Sadanga", province: "MOU", region: "CAR" },
  { name: "Sagada", province: "MOU", region: "CAR" },
  { name: "Tadian", province: "MOU", region: "CAR" },
  { name: "Adams", province: "ILN", region: "I" },
  { name: "Bacarra", province: "ILN", region: "I" },
  { name: "Badoc", province: "ILN", region: "I" },
  { name: "Bangui", province: "ILN", region: "I" },
  { name: "Banna", province: "ILN", region: "I" },
  { name: "Batac", province: "ILN", city: true, region: "I" },
  { name: "Burgos", province: "ILN", region: "I" },
  { name: "Carasi", province: "ILN", region: "I" },
  { name: "Currimao", province: "ILN", region: "I" },
  { name: "Dingras", province: "ILN", region: "I" },
  { name: "Dumalneg", province: "ILN", region: "I" },
  { name: "Laoag", province: "ILN", city: true, region: "I" },
  { name: "Marcos", province: "ILN", region: "I" },
  { name: "Nueva Era", province: "ILN", region: "I" },
  { name: "Pagudpud", province: "ILN", region: "I" },
  { name: "Paoay", province: "ILN", region: "I" },
  { name: "Pasuquin", province: "ILN", region: "I" },
  { name: "Piddig", province: "ILN", region: "I" },
  { name: "Pinili", province: "ILN", region: "I" },
  { name: "San Nicolas", province: "ILN", region: "I" },
  { name: "Sarrat", province: "ILN", region: "I" },
  { name: "Solsona", province: "ILN", region: "I" },
  { name: "Vintar", province: "ILN", region: "I" },
  { name: "Alilem", province: "ILS", region: "I" },
  { name: "Banayoyo", province: "ILS", region: "I" },
  { name: "Bantay", province: "ILS", region: "I" },
  { name: "Burgos", province: "ILS", region: "I" },
  { name: "Cabugao", province: "ILS", region: "I" },
  { name: "Candon", province: "ILS", city: true, region: "I" },
  { name: "Caoayan", province: "ILS", region: "I" },
  { name: "Cervantes", province: "ILS", region: "I" },
  { name: "Galimuyod", province: "ILS", region: "I" },
  { name: "Gregorio Del Pilar", province: "ILS", region: "I" },
  { name: "Lidlidda", province: "ILS", region: "I" },
  { name: "Magsingal", province: "ILS", region: "I" },
  { name: "Nagbukel", province: "ILS", region: "I" },
  { name: "Narvacan", province: "ILS", region: "I" },
  { name: "Quirino", province: "ILS", region: "I" },
  { name: "Salcedo", province: "ILS", region: "I" },
  { name: "San Emilio", province: "ILS", region: "I" },
  { name: "San Esteban", province: "ILS", region: "I" },
  { name: "San Ildefonso", province: "ILS", region: "I" },
  { name: "San Juan", province: "ILS", region: "I" },
  { name: "San Vicente", province: "ILS", region: "I" },
  { name: "Santa", province: "ILS", region: "I" },
  { name: "Santa Catalina", province: "ILS", region: "I" },
  { name: "Santa Cruz", province: "ILS", region: "I" },
  { name: "Santa Lucia", province: "ILS", region: "I" },
  { name: "Santa Maria", province: "ILS", region: "I" },
  { name: "Santiago", province: "ILS", region: "I" },
  { name: "Santo Domingo", province: "ILS", region: "I" },
  { name: "Sigay", province: "ILS", region: "I" },
  { name: "Sinait", province: "ILS", region: "I" },
  { name: "Sugpon", province: "ILS", region: "I" },
  { name: "Suyo", province: "ILS", region: "I" },
  { name: "Tagudin", province: "ILS", region: "I" },
  { name: "Vigan", province: "ILS", city: true, region: "I" },
  { name: "Agoo", province: "LUN", region: "I" },
  { name: "Aringay", province: "LUN", region: "I" },
  { name: "Bacnotan", province: "LUN", region: "I" },
  { name: "Bagulin", province: "LUN", region: "I" },
  { name: "Balaoan", province: "LUN", region: "I" },
  { name: "Bangar", province: "LUN", region: "I" },
  { name: "Bauang", province: "LUN", region: "I" },
  { name: "Burgos", province: "LUN", region: "I" },
  { name: "Caba", province: "LUN", region: "I" },
  { name: "Luna", province: "LUN", region: "I" },
  { name: "Naguilian", province: "LUN", region: "I" },
  { name: "Pugo", province: "LUN", region: "I" },
  { name: "Rosario", province: "LUN", region: "I" },
  { name: "San Fernando", province: "LUN", city: true, region: "I" },
  { name: "San Gabriel", province: "LUN", region: "I" },
  { name: "San Juan", province: "LUN", region: "I" },
  { name: "Santo Tomas", province: "LUN", region: "I" },
  { name: "Santol", province: "LUN", region: "I" },
  { name: "Sudipen", province: "LUN", region: "I" },
  { name: "Tubao", province: "LUN", region: "I" },
  { name: "Agno", province: "PAN", region: "I" },
  { name: "Aguilar", province: "PAN", region: "I" },
  { name: "Alaminos", province: "PAN", city: true, region: "I" },
  { name: "Alcala", province: "PAN", region: "I" },
  { name: "Anda", province: "PAN", region: "I" },
  { name: "Asingan", province: "PAN", region: "I" },
  { name: "Balungao", province: "PAN", region: "I" },
  { name: "Bani", province: "PAN", region: "I" },
  { name: "Basista", province: "PAN", region: "I" },
  { name: "Bautista", province: "PAN", region: "I" },
  { name: "Bayambang", province: "PAN", region: "I" },
  { name: "Binalonan", province: "PAN", region: "I" },
  { name: "Binmaley", province: "PAN", region: "I" },
  { name: "Bolinao", province: "PAN", region: "I" },
  { name: "Bugallon", province: "PAN", region: "I" },
  { name: "Burgos", province: "PAN", region: "I" },
  { name: "Calasiao", province: "PAN", region: "I" },
  { name: "Dagupan", province: "PAN", city: true, region: "I" },
  { name: "Dasol", province: "PAN", region: "I" },
  { name: "Infanta", province: "PAN", region: "I" },
  { name: "Labrador", province: "PAN", region: "I" },
  { name: "Laoac", province: "PAN", region: "I" },
  { name: "Lingayen", province: "PAN", region: "I" },
  { name: "Mabini", province: "PAN", region: "I" },
  { name: "Malasiqui", province: "PAN", region: "I" },
  { name: "Manaoag", province: "PAN", region: "I" },
  { name: "Mangaldan", province: "PAN", region: "I" },
  { name: "Mangatarem", province: "PAN", region: "I" },
  { name: "Mapandan", province: "PAN", region: "I" },
  { name: "Natividad", province: "PAN", region: "I" },
  { name: "Pozzorubio", province: "PAN", region: "I" },
  { name: "Rosales", province: "PAN", region: "I" },
  { name: "San Carlos", province: "PAN", city: true, region: "I" },
  { name: "San Fabian", province: "PAN", region: "I" },
  { name: "San Jacinto", province: "PAN", region: "I" },
  { name: "San Manuel", province: "PAN", region: "I" },
  { name: "San Nicolas", province: "PAN", region: "I" },
  { name: "San Quintin", province: "PAN", region: "I" },
  { name: "Santa Barbara", province: "PAN", region: "I" },
  { name: "Santa Maria", province: "PAN", region: "I" },
  { name: "Santo Tomas", province: "PAN", region: "I" },
  { name: "Sison", province: "PAN", region: "I" },
  { name: "Sual", province: "PAN", region: "I" },
  { name: "Tayug", province: "PAN", region: "I" },
  { name: "Umingan", province: "PAN", region: "I" },
  { name: "Urdaneta", province: "PAN", city: true, region: "I" },
  { name: "Urbiztondo", province: "PAN", region: "I" },
  { name: "Villasis", province: "PAN", region: "I" },
  { name: "Basco", province: "BTN", region: "II" },
  { name: "Itbayat", province: "BTN", region: "II" },
  { name: "Ivana", province: "BTN", region: "II" },
  { name: "Mahatao", province: "BTN", region: "II" },
  { name: "Sabtang", province: "BTN", region: "II" },
  { name: "Uyugan", province: "BTN", region: "II" },
  { name: "Abulug", province: "CAG", region: "II" },
  { name: "Alcala", province: "CAG", region: "II" },
  { name: "Allacapan", province: "CAG", region: "II" },
  { name: "Amulung", province: "CAG", region: "II" },
  { name: "Aparri", province: "CAG", region: "II" },
  { name: "Baggao", province: "CAG", region: "II" },
  { name: "Ballesteros", province: "CAG", region: "II" },
  { name: "Buguey", province: "CAG", region: "II" },
  { name: "Calayan", province: "CAG", region: "II" },
  { name: "Camalaniugan", province: "CAG", region: "II" },
  { name: "Claveria", province: "CAG", region: "II" },
  { name: "Enrile", province: "CAG", region: "II" },
  { name: "Gattaran", province: "CAG", region: "II" },
  { name: "Gonzaga", province: "CAG", region: "II" },
  { name: "Iguig", province: "CAG", region: "II" },
  { name: "Lal-lo", province: "CAG", region: "II" },
  { name: "Lasam", province: "CAG", region: "II" },
  { name: "Pamplona", province: "CAG", region: "II" },
  { name: "Peñablanca", province: "CAG", region: "II" },
  { name: "Piat", province: "CAG", region: "II" },
  { name: "Rizal", province: "CAG", region: "II" },
  { name: "Sanchez-Mira", province: "CAG", region: "II" },
  { name: "Santa Ana", province: "CAG", region: "II" },
  { name: "Santa Praxedes", province: "CAG", region: "II" },
  { name: "Santa Teresita", province: "CAG", region: "II" },
  { name: "Santo Niño", province: "CAG", region: "II" },
  { name: "Solana", province: "CAG", region: "II" },
  { name: "Tuao", province: "CAG", region: "II" },
  { name: "Tuguegarao", province: "CAG", city: true, region: "II" },
  { name: "Alicia", province: "ISA", region: "II" },
  { name: "Angadanan", province: "ISA", region: "II" },
  { name: "Aurora", province: "ISA", region: "II" },
  { name: "Benito Soliven", province: "ISA", region: "II" },
  { name: "Burgos", province: "ISA", region: "II" },
  { name: "Cabagan", province: "ISA", region: "II" },
  { name: "Cabatuan", province: "ISA", region: "II" },
  { name: "Cauayan", province: "ISA", city: true, region: "II" },
  { name: "Cordon", province: "ISA", region: "II" },
  { name: "Delfin Albano", province: "ISA", region: "II" },
  { name: "Dinapigue", province: "ISA", region: "II" },
  { name: "Divilacan", province: "ISA", region: "II" },
  { name: "Echague", province: "ISA", region: "II" },
  { name: "Gamu", province: "ISA", region: "II" },
  { name: "Ilagan", province: "ISA", city: true, region: "II" },
  { name: "Jones", province: "ISA", region: "II" },
  { name: "Luna", province: "ISA", region: "II" },
  { name: "Maconacon", province: "ISA", region: "II" },
  { name: "Mallig", province: "ISA", region: "II" },
  { name: "Naguilian", province: "ISA", region: "II" },
  { name: "Palanan", province: "ISA", region: "II" },
  { name: "Quezon", province: "ISA", region: "II" },
  { name: "Quirino", province: "ISA", region: "II" },
  { name: "Ramon", province: "ISA", region: "II" },
  { name: "Reina Mercedes", province: "ISA", region: "II" },
  { name: "Roxas", province: "ISA", region: "II" },
  { name: "San Agustin", province: "ISA", region: "II" },
  { name: "San Guillermo", province: "ISA", region: "II" },
  { name: "San Isidro", province: "ISA", region: "II" },
  { name: "San Manuel", province: "ISA", region: "II" },
  { name: "San Mariano", province: "ISA", region: "II" },
  { name: "San Mateo", province: "ISA", region: "II" },
  { name: "San Pablo", province: "ISA", region: "II" },
  { name: "Santa Maria", province: "ISA", region: "II" },
  { name: "Santiago", province: "ISA", city: true, region: "II" },
  { name: "Santo Tomas", province: "ISA", region: "II" },
  { name: "Tumauini", province: "ISA", region: "II" },
  { name: "Alfonso Castaneda", province: "NUV", region: "II" },
  { name: "Ambaguio", province: "NUV", region: "II" },
  { name: "Aritao", province: "NUV", region: "II" },
  { name: "Bagabag", province: "NUV", region: "II" },
  { name: "Bambang", province: "NUV", region: "II" },
  { name: "Bayombong", province: "NUV", region: "II" },
  { name: "Diadi", province: "NUV", region: "II" },
  { name: "Dupax del Norte", province: "NUV", region: "II" },
  { name: "Dupax del Sur", province: "NUV", region: "II" },
  { name: "Kasibu", province: "NUV", region: "II" },
  { name: "Kayapa", province: "NUV", region: "II" },
  { name: "Quezon", province: "NUV", region: "II" },
  { name: "Santa Fe", province: "NUV", region: "II" },
  { name: "Solano", province: "NUV", region: "II" },
  { name: "Villaverde", province: "NUV", region: "II" },
  { name: "Aglipay", province: "QUI", region: "II" },
  { name: "Cabarroguis", province: "QUI", region: "II" },
  { name: "Diffun", province: "QUI", region: "II" },
  { name: "Maddela", province: "QUI", region: "II" },
  { name: "Nagtipunan", province: "QUI", region: "II" },
  { name: "Saguday", province: "QUI", region: "II" },
  { name: "Baler", province: "AUR", region: "III" },
  { name: "Casiguran", province: "AUR", region: "III" },
  { name: "Dilasag", province: "AUR", region: "III" },
  { name: "Dinalungan", province: "AUR", region: "III" },
  { name: "Dingalan", province: "AUR", region: "III" },
  { name: "Dipaculao", province: "AUR", region: "III" },
  { name: "Maria Aurora", province: "AUR", region: "III" },
  { name: "San Luis", province: "AUR", region: "III" },
  { name: "Abucay", province: "BAN", region: "III" },
  { name: "Bagac", province: "BAN", region: "III" },
  { name: "Balanga", province: "BAN", city: true, region: "III" },
  { name: "Dinalupihan", province: "BAN", region: "III" },
  { name: "Hermosa", province: "BAN", region: "III" },
  { name: "Limay", province: "BAN", region: "III" },
  { name: "Mariveles", province: "BAN", region: "III" },
  { name: "Morong", province: "BAN", region: "III" },
  { name: "Orani", province: "BAN", region: "III" },
  { name: "Orion", province: "BAN", region: "III" },
  { name: "Pilar", province: "BAN", region: "III" },
  { name: "Samal", province: "BAN", region: "III" },
  { name: "Angat", province: "BUL", region: "III" },
  { name: "Balagtas", province: "BUL", region: "III" },
  { name: "Baliuag", province: "BUL", region: "III" },
  { name: "Bocaue", province: "BUL", region: "III" },
  { name: "Bulakan", province: "BUL", region: "III" },
  { name: "Bustos", province: "BUL", region: "III" },
  { name: "Calumpit", province: "BUL", region: "III" },
  { name: "Doña Remedios Trinidad", province: "BUL", region: "III" },
  { name: "Guiguinto", province: "BUL", region: "III" },
  { name: "Hagonoy", province: "BUL", region: "III" },
  { name: "Malolos", province: "BUL", city: true, region: "III" },
  { name: "Marilao", province: "BUL", region: "III" },
  { name: "Meycauayan", province: "BUL", city: true, region: "III" },
  { name: "Norzagaray", province: "BUL", region: "III" },
  { name: "Obando", province: "BUL", region: "III" },
  { name: "Pandi", province: "BUL", region: "III" },
  { name: "Paombong", province: "BUL", region: "III" },
  { name: "Plaridel", province: "BUL", region: "III" },
  { name: "Pulilan", province: "BUL", region: "III" },
  { name: "San Ildefonso", province: "BUL", region: "III" },
  { name: "San Jose del Monte", province: "BUL", city: true, region: "III" },
  { name: "San Miguel", province: "BUL", region: "III" },
  { name: "San Rafael", province: "BUL", region: "III" },
  { name: "Santa Maria", province: "BUL", region: "III" },
  { name: "Aliaga", province: "NUE", region: "III" },
  { name: "Bongabon", province: "NUE", region: "III" },
  { name: "Cabanatuan", province: "NUE", city: true, region: "III" },
  { name: "Cabiao", province: "NUE", region: "III" },
  { name: "Carranglan", province: "NUE", region: "III" },
  { name: "Cuyapo", province: "NUE", region: "III" },
  { name: "Gabaldon", province: "NUE", region: "III" },
  { name: "Gapan", province: "NUE", city: true, region: "III" },
  { name: "General Mamerto Natividad", province: "NUE", region: "III" },
  { name: "General Tinio", province: "NUE", region: "III" },
  { name: "Guimba", province: "NUE", region: "III" },
  { name: "Jaen", province: "NUE", region: "III" },
  { name: "Laur", province: "NUE", region: "III" },
  { name: "Licab", province: "NUE", region: "III" },
  { name: "Llanera", province: "NUE", region: "III" },
  { name: "Lupao", province: "NUE", region: "III" },
  { name: "Muñoz", province: "NUE", city: true, region: "III" },
  { name: "Nampicuan", province: "NUE", region: "III" },
  { name: "Palayan", province: "NUE", city: true, region: "III" },
  { name: "Pantabangan", province: "NUE", region: "III" },
  { name: "Peñaranda", province: "NUE", region: "III" },
  { name: "Quezon", province: "NUE", region: "III" },
  { name: "Rizal", province: "NUE", region: "III" },
  { name: "San Antonio", province: "NUE", region: "III" },
  { name: "San Isidro", province: "NUE", region: "III" },
  { name: "San Jose", province: "NUE", city: true, region: "III" },
  { name: "San Leonardo", province: "NUE", region: "III" },
  { name: "Santa Rosa", province: "NUE", region: "III" },
  { name: "Santo Domingo", province: "NUE", region: "III" },
  { name: "Talavera", province: "NUE", region: "III" },
  { name: "Talugtug", province: "NUE", region: "III" },
  { name: "Zaragoza", province: "NUE", region: "III" },
  { name: "Angeles", province: "PAM", city: true, region: "III" },
  { name: "Apalit", province: "PAM", region: "III" },
  { name: "Arayat", province: "PAM", region: "III" },
  { name: "Bacolor", province: "PAM", region: "III" },
  { name: "Candaba", province: "PAM", region: "III" },
  { name: "Floridablanca", province: "PAM", region: "III" },
  { name: "Guagua", province: "PAM", region: "III" },
  { name: "Lubao", province: "PAM", region: "III" },
  { name: "Mabalacat", province: "PAM", city: true, region: "III" },
  { name: "Macabebe", province: "PAM", region: "III" },
  { name: "Magalang", province: "PAM", region: "III" },
  { name: "Masantol", province: "PAM", region: "III" },
  { name: "Mexico", province: "PAM", region: "III" },
  { name: "Minalin", province: "PAM", region: "III" },
  { name: "Porac", province: "PAM", region: "III" },
  { name: "San Fernando", province: "PAM", city: true, region: "III" },
  { name: "San Luis", province: "PAM", region: "III" },
  { name: "San Simon", province: "PAM", region: "III" },
  { name: "Santa Ana", province: "PAM", region: "III" },
  { name: "Santa Rita", province: "PAM", region: "III" },
  { name: "Santo Tomas", province: "PAM", region: "III" },
  { name: "Sasmuan", province: "PAM", region: "III" },
  { name: "Anao", province: "TAR", region: "III" },
  { name: "Bamban", province: "TAR", region: "III" },
  { name: "Camiling", province: "TAR", region: "III" },
  { name: "Capas", province: "TAR", region: "III" },
  { name: "Concepcion", province: "TAR", region: "III" },
  { name: "Gerona", province: "TAR", region: "III" },
  { name: "La Paz", province: "TAR", region: "III" },
  { name: "Mayantoc", province: "TAR", region: "III" },
  { name: "Moncada", province: "TAR", region: "III" },
  { name: "Paniqui", province: "TAR", region: "III" },
  { name: "Pura", province: "TAR", region: "III" },
  { name: "Ramos", province: "TAR", region: "III" },
  { name: "San Clemente", province: "TAR", region: "III" },
  { name: "San Jose", province: "TAR", region: "III" },
  { name: "San Manuel", province: "TAR", region: "III" },
  { name: "Santa Ignacia", province: "TAR", region: "III" },
  { name: "Tarlac", province: "TAR", city: true, region: "III" },
  { name: "Victoria", province: "TAR", region: "III" },
  { name: "Botolan", province: "ZMB", region: "III" },
  { name: "Cabangan", province: "ZMB", region: "III" },
  { name: "Candelaria", province: "ZMB", region: "III" },
  { name: "Castillejos", province: "ZMB", region: "III" },
  { name: "Iba", province: "ZMB", region: "III" },
  { name: "Masinloc", province: "ZMB", region: "III" },
  { name: "Olongapo", province: "ZMB", city: true, region: "III" },
  { name: "Palauig", province: "ZMB", region: "III" },
  { name: "San Antonio", province: "ZMB", region: "III" },
  { name: "San Felipe", province: "ZMB", region: "III" },
  { name: "San Marcelino", province: "ZMB", region: "III" },
  { name: "San Narciso", province: "ZMB", region: "III" },
  { name: "Santa Cruz", province: "ZMB", region: "III" },
  { name: "Subic", province: "ZMB", region: "III" },
  { name: "Agoncillo", province: "BTG", region: "IV-A" },
  { name: "Alitagtag", province: "BTG", region: "IV-A" },
  { name: "Balayan", province: "BTG", region: "IV-A" },
  { name: "Balete", province: "BTG", region: "IV-A" },
  { name: "Batangas", province: "BTG", city: true, region: "IV-A" },
  { name: "Bauan", province: "BTG", region: "IV-A" },
  { name: "Calaca", province: "BTG", region: "IV-A" },
  { name: "Calatagan", province: "BTG", region: "IV-A" },
  { name: "Cuenca", province: "BTG", region: "IV-A" },
  { name: "Ibaan", province: "BTG", region: "IV-A" },
  { name: "Laurel", province: "BTG", region: "IV-A" },
  { name: "Lemery", province: "BTG", region: "IV-A" },
  { name: "Lian", province: "BTG", region: "IV-A" },
  { name: "Lipa", province: "BTG", city: true, region: "IV-A" },
  { name: "Lobo", province: "BTG", region: "IV-A" },
  { name: "Mabini", province: "BTG", region: "IV-A" },
  { name: "Malvar", province: "BTG", region: "IV-A" },
  { name: "Mataasnakahoy", province: "BTG", region: "IV-A" },
  { name: "Nasugbu", province: "BTG", region: "IV-A" },
  { name: "Padre Garcia", province: "BTG", region: "IV-A" },
  { name: "Rosario", province: "BTG", region: "IV-A" },
  { name: "San Jose", province: "BTG", region: "IV-A" },
  { name: "San Juan", province: "BTG", region: "IV-A" },
  { name: "San Luis", province: "BTG", region: "IV-A" },
  { name: "San Nicolas", province: "BTG", region: "IV-A" },
  { name: "San Pascual", province: "BTG", region: "IV-A" },
  { name: "Santa Teresita", province: "BTG", region: "IV-A" },
  { name: "Santo Tomas", province: "BTG", region: "IV-A" },
  { name: "Taal", province: "BTG", region: "IV-A" },
  { name: "Talisay", province: "BTG", region: "IV-A" },
  { name: "Tanauan", province: "BTG", city: true, region: "IV-A" },
  { name: "Taysan", province: "BTG", region: "IV-A" },
  { name: "Tingloy", province: "BTG", region: "IV-A" },
  { name: "Tuy", province: "BTG", region: "IV-A" },
  { name: "Alfonso", province: "CAV", region: "IV-A" },
  { name: "Amadeo", province: "CAV", region: "IV-A" },
  { name: "Bacoor", province: "CAV", city: true, region: "IV-A" },
  { name: "Carmona", province: "CAV", region: "IV-A" },
  { name: "Cavite", province: "CAV", city: true, region: "IV-A" },
  { name: "Dasmariñas", province: "CAV", city: true, region: "IV-A" },
  { name: "General Mariano Alvarez", province: "CAV", region: "IV-A" },
  { name: "General Emilio Aguinaldo", province: "CAV", region: "IV-A" },
  { name: "General Trias", province: "CAV", region: "IV-A" },
  { name: "Imus", province: "CAV", city: true, region: "IV-A" },
  { name: "Indang", province: "CAV", region: "IV-A" },
  { name: "Kawit", province: "CAV", region: "IV-A" },
  { name: "Magallanes", province: "CAV", region: "IV-A" },
  { name: "Maragondon", province: "CAV", region: "IV-A" },
  { name: "Mendez", province: "CAV", region: "IV-A" },
  { name: "Naic", province: "CAV", region: "IV-A" },
  { name: "Noveleta", province: "CAV", region: "IV-A" },
  { name: "Rosario", province: "CAV", region: "IV-A" },
  { name: "Silang", province: "CAV", region: "IV-A" },
  { name: "Tagaytay", province: "CAV", city: true, region: "IV-A" },
  { name: "Tanza", province: "CAV", region: "IV-A" },
  { name: "Ternate", province: "CAV", region: "IV-A" },
  { name: "Trece Martires", province: "CAV", city: true, region: "IV-A" },
  { name: "Alaminos", province: "LAG", region: "IV-A" },
  { name: "Bay", province: "LAG", region: "IV-A" },
  { name: "Biñan", province: "LAG", city: true, region: "IV-A" },
  { name: "Cabuyao", province: "LAG", city: true, region: "IV-A" },
  { name: "Calamba", province: "LAG", city: true, region: "IV-A" },
  { name: "Calauan", province: "LAG", region: "IV-A" },
  { name: "Cavinti", province: "LAG", region: "IV-A" },
  { name: "Famy", province: "LAG", region: "IV-A" },
  { name: "Kalayaan", province: "LAG", region: "IV-A" },
  { name: "Liliw", province: "LAG", region: "IV-A" },
  { name: "Los Baños", province: "LAG", region: "IV-A" },
  { name: "Luisiana", province: "LAG", region: "IV-A" },
  { name: "Lumban", province: "LAG", region: "IV-A" },
  { name: "Mabitac", province: "LAG", region: "IV-A" },
  { name: "Magdalena", province: "LAG", region: "IV-A" },
  { name: "Majayjay", province: "LAG", region: "IV-A" },
  { name: "Nagcarlan", province: "LAG", region: "IV-A" },
  { name: "Paete", province: "LAG", region: "IV-A" },
  { name: "Pagsanjan", province: "LAG", region: "IV-A" },
  { name: "Pakil", province: "LAG", region: "IV-A" },
  { name: "Pangil", province: "LAG", region: "IV-A" },
  { name: "Pila", province: "LAG", region: "IV-A" },
  { name: "Rizal", province: "LAG", region: "IV-A" },
  { name: "San Pablo", province: "LAG", city: true, region: "IV-A" },
  { name: "San Pedro", province: "LAG", city: true, region: "IV-A" },
  { name: "Santa Cruz", province: "LAG", region: "IV-A" },
  { name: "Santa Maria", province: "LAG", region: "IV-A" },
  { name: "Santa Rosa", province: "LAG", city: true, region: "IV-A" },
  { name: "Siniloan", province: "LAG", region: "IV-A" },
  { name: "Victoria", province: "LAG", region: "IV-A" },
  { name: "Agdangan", province: "QUE", region: "IV-A" },
  { name: "Alabat", province: "QUE", region: "IV-A" },
  { name: "Atimonan", province: "QUE", region: "IV-A" },
  { name: "Buenavista", province: "QUE", region: "IV-A" },
  { name: "Burdeos", province: "QUE", region: "IV-A" },
  { name: "Calauag", province: "QUE", region: "IV-A" },
  { name: "Candelaria", province: "QUE", region: "IV-A" },
  { name: "Catanauan", province: "QUE", region: "IV-A" },
  { name: "Dolores", province: "QUE", region: "IV-A" },
  { name: "General Luna", province: "QUE", region: "IV-A" },
  { name: "General Nakar", province: "QUE", region: "IV-A" },
  { name: "Guinayangan", province: "QUE", region: "IV-A" },
  { name: "Gumaca", province: "QUE", region: "IV-A" },
  { name: "Infanta", province: "QUE", region: "IV-A" },
  { name: "Jomalig", province: "QUE", region: "IV-A" },
  { name: "Lopez", province: "QUE", region: "IV-A" },
  { name: "Lucban", province: "QUE", region: "IV-A" },
  { name: "Lucena", province: "QUE", city: true, region: "IV-A" },
  { name: "Macalelon", province: "QUE", region: "IV-A" },
  { name: "Mauban", province: "QUE", region: "IV-A" },
  { name: "Mulanay", province: "QUE", region: "IV-A" },
  { name: "Padre Burgos", province: "QUE", region: "IV-A" },
  { name: "Pagbilao", province: "QUE", region: "IV-A" },
  { name: "Panukulan", province: "QUE", region: "IV-A" },
  { name: "Patnanungan", province: "QUE", region: "IV-A" },
  { name: "Perez", province: "QUE", region: "IV-A" },
  { name: "Pitogo", province: "QUE", region: "IV-A" },
  { name: "Plaridel", province: "QUE", region: "IV-A" },
  { name: "Polillo", province: "QUE", region: "IV-A" },
  { name: "Quezon", province: "QUE", region: "IV-A" },
  { name: "Real", province: "QUE", region: "IV-A" },
  { name: "Sampaloc", province: "QUE", region: "IV-A" },
  { name: "San Andres", province: "QUE", region: "IV-A" },
  { name: "San Antonio", province: "QUE", region: "IV-A" },
  { name: "San Francisco", province: "QUE", region: "IV-A" },
  { name: "San Narciso", province: "QUE", region: "IV-A" },
  { name: "Sariaya", province: "QUE", region: "IV-A" },
  { name: "Tagkawayan", province: "QUE", region: "IV-A" },
  { name: "Tayabas", province: "QUE", city: true, region: "IV-A" },
  { name: "Tiaong", province: "QUE", region: "IV-A" },
  { name: "Unisan", province: "QUE", region: "IV-A" },
  { name: "Angono", province: "RIZ", region: "IV-A" },
  { name: "Antipolo", province: "RIZ", city: true, region: "IV-A" },
  { name: "Baras", province: "RIZ", region: "IV-A" },
  { name: "Binangonan", province: "RIZ", region: "IV-A" },
  { name: "Cainta", province: "RIZ", region: "IV-A" },
  { name: "Cardona", province: "RIZ", region: "IV-A" },
  { name: "Jalajala", province: "RIZ", region: "IV-A" },
  { name: "Morong", province: "RIZ", region: "IV-A" },
  { name: "Pililla", province: "RIZ", region: "IV-A" },
  { name: "Rodriguez", province: "RIZ", region: "IV-A" },
  { name: "San Mateo", province: "RIZ", region: "IV-A" },
  { name: "Tanay", province: "RIZ", region: "IV-A" },
  { name: "Taytay", province: "RIZ", region: "IV-A" },
  { name: "Teresa", province: "RIZ", region: "IV-A" },
  { name: "Boac", province: "MAD", region: "IV-B" },
  { name: "Buenavista", province: "MAD", region: "IV-B" },
  { name: "Gasan", province: "MAD", region: "IV-B" },
  { name: "Mogpog", province: "MAD", region: "IV-B" },
  { name: "Santa Cruz", province: "MAD", region: "IV-B" },
  { name: "Torrijos", province: "MAD", region: "IV-B" },
  { name: "Abra de Ilog", province: "MDC", region: "IV-B" },
  { name: "Calintaan", province: "MDC", region: "IV-B" },
  { name: "Looc", province: "MDC", region: "IV-B" },
  { name: "Lubang", province: "MDC", region: "IV-B" },
  { name: "Magsaysay", province: "MDC", region: "IV-B" },
  { name: "Mamburao", province: "MDC", region: "IV-B" },
  { name: "Paluan", province: "MDC", region: "IV-B" },
  { name: "Rizal", province: "MDC", region: "IV-B" },
  { name: "Sablayan", province: "MDC", region: "IV-B" },
  { name: "San Jose", province: "MDC", region: "IV-B" },
  { name: "Santa Cruz", province: "MDC", region: "IV-B" },
  { name: "Baco", province: "MDR", region: "IV-B" },
  { name: "Bansud", province: "MDR", region: "IV-B" },
  { name: "Bongabong", province: "MDR", region: "IV-B" },
  { name: "Bulalacao", province: "MDR", region: "IV-B" },
  { name: "Calapan", province: "MDR", city: true, region: "IV-B" },
  { name: "Gloria", province: "MDR", region: "IV-B" },
  { name: "Mansalay", province: "MDR", region: "IV-B" },
  { name: "Naujan", province: "MDR", region: "IV-B" },
  { name: "Pinamalayan", province: "MDR", region: "IV-B" },
  { name: "Pola", province: "MDR", region: "IV-B" },
  { name: "Puerto Galera", province: "MDR", region: "IV-B" },
  { name: "Roxas", province: "MDR", region: "IV-B" },
  { name: "San Teodoro", province: "MDR", region: "IV-B" },
  { name: "Socorro", province: "MDR", region: "IV-B" },
  { name: "Victoria", province: "MDR", region: "IV-B" },
  { name: "Aborlan", province: "PLW", region: "IV-B" },
  { name: "Agutaya", province: "PLW", region: "IV-B" },
  { name: "Araceli", province: "PLW", region: "IV-B" },
  { name: "Balabac", province: "PLW", region: "IV-B" },
  { name: "Bataraza", province: "PLW", region: "IV-B" },
  { name: "Brooke's Point", province: "PLW", region: "IV-B" },
  { name: "Busuanga", province: "PLW", region: "IV-B" },
  { name: "Cagayancillo", province: "PLW", region: "IV-B" },
  { name: "Coron", province: "PLW", region: "IV-B" },
  { name: "Culion", province: "PLW", region: "IV-B" },
  { name: "Cuyo", province: "PLW", region: "IV-B" },
  { name: "Dumaran", province: "PLW", region: "IV-B" },
  { name: "El Nido", province: "PLW", region: "IV-B" },
  { name: "Kalayaan", province: "PLW", region: "IV-B" },
  { name: "Linapacan", province: "PLW", region: "IV-B" },
  { name: "Magsaysay", province: "PLW", region: "IV-B" },
  { name: "Narra", province: "PLW", region: "IV-B" },
  { name: "Puerto Princesa", province: "PLW", city: true, region: "IV-B" },
  { name: "Quezon", province: "PLW", region: "IV-B" },
  { name: "Rizal", province: "PLW", region: "IV-B" },
  { name: "Roxas", province: "PLW", region: "IV-B" },
  { name: "San Vicente", province: "PLW", region: "IV-B" },
  { name: "Sofronio Española", province: "PLW", region: "IV-B" },
  { name: "Taytay", province: "PLW", region: "IV-B" },
  { name: "Alcantara", province: "ROM", region: "IV-B" },
  { name: "Banton", province: "ROM", region: "IV-B" },
  { name: "Cajidiocan", province: "ROM", region: "IV-B" },
  { name: "Calatrava", province: "ROM", region: "IV-B" },
  { name: "Concepcion", province: "ROM", region: "IV-B" },
  { name: "Corcuera", province: "ROM", region: "IV-B" },
  { name: "Ferrol", province: "ROM", region: "IV-B" },
  { name: "Looc", province: "ROM", region: "IV-B" },
  { name: "Magdiwang", province: "ROM", region: "IV-B" },
  { name: "Odiongan", province: "ROM", region: "IV-B" },
  { name: "Romblon", province: "ROM", region: "IV-B" },
  { name: "San Agustin", province: "ROM", region: "IV-B" },
  { name: "San Andres", province: "ROM", region: "IV-B" },
  { name: "San Fernando", province: "ROM", region: "IV-B" },
  { name: "San Jose", province: "ROM", region: "IV-B" },
  { name: "Santa Fe", province: "ROM", region: "IV-B" },
  { name: "Santa Maria", province: "ROM", region: "IV-B" },
  { name: "Bacacay", province: "ALB", region: "V" },
  { name: "Camalig", province: "ALB", region: "V" },
  { name: "Daraga", province: "ALB", region: "V" },
  { name: "Guinobatan", province: "ALB", region: "V" },
  { name: "Jovellar", province: "ALB", region: "V" },
  { name: "Legazpi", province: "ALB", city: true, region: "V" },
  { name: "Libon", province: "ALB", region: "V" },
  { name: "Ligao", province: "ALB", city: true, region: "V" },
  { name: "Malilipot", province: "ALB", region: "V" },
  { name: "Malinao", province: "ALB", region: "V" },
  { name: "Manito", province: "ALB", region: "V" },
  { name: "Oas", province: "ALB", region: "V" },
  { name: "Pio Duran", province: "ALB", region: "V" },
  { name: "Polangui", province: "ALB", region: "V" },
  { name: "Rapu-Rapu", province: "ALB", region: "V" },
  { name: "Santo Domingo", province: "ALB", region: "V" },
  { name: "Tabaco", province: "ALB", city: true, region: "V" },
  { name: "Tiwi", province: "ALB", region: "V" },
  { name: "Basud", province: "CAN", region: "V" },
  { name: "Capalonga", province: "CAN", region: "V" },
  { name: "Daet", province: "CAN", region: "V" },
  { name: "Jose Panganiban", province: "CAN", region: "V" },
  { name: "Labo", province: "CAN", region: "V" },
  { name: "Mercedes", province: "CAN", region: "V" },
  { name: "Paracale", province: "CAN", region: "V" },
  { name: "San Lorenzo Ruiz", province: "CAN", region: "V" },
  { name: "San Vicente", province: "CAN", region: "V" },
  { name: "Santa Elena", province: "CAN", region: "V" },
  { name: "Talisay", province: "CAN", region: "V" },
  { name: "Vinzons", province: "CAN", region: "V" },
  { name: "Baao", province: "CAS", region: "V" },
  { name: "Balatan", province: "CAS", region: "V" },
  { name: "Bato", province: "CAS", region: "V" },
  { name: "Bombon", province: "CAS", region: "V" },
  { name: "Buhi", province: "CAS", region: "V" },
  { name: "Bula", province: "CAS", region: "V" },
  { name: "Cabusao", province: "CAS", region: "V" },
  { name: "Calabanga", province: "CAS", region: "V" },
  { name: "Camaligan", province: "CAS", region: "V" },
  { name: "Canaman", province: "CAS", region: "V" },
  { name: "Caramoan", province: "CAS", region: "V" },
  { name: "Del Gallego", province: "CAS", region: "V" },
  { name: "Gainza", province: "CAS", region: "V" },
  { name: "Garchitorena", province: "CAS", region: "V" },
  { name: "Goa", province: "CAS", region: "V" },
  { name: "Iriga", province: "CAS", city: true, region: "V" },
  { name: "Lagonoy", province: "CAS", region: "V" },
  { name: "Libmanan", province: "CAS", region: "V" },
  { name: "Lupi", province: "CAS", region: "V" },
  { name: "Magarao", province: "CAS", region: "V" },
  { name: "Milaor", province: "CAS", region: "V" },
  { name: "Minalabac", province: "CAS", region: "V" },
  { name: "Nabua", province: "CAS", region: "V" },
  { name: "Naga", province: "CAS", city: true, region: "V" },
  { name: "Ocampo", province: "CAS", region: "V" },
  { name: "Pamplona", province: "CAS", region: "V" },
  { name: "Pasacao", province: "CAS", region: "V" },
  { name: "Pili", province: "CAS", region: "V" },
  { name: "Presentacion", province: "CAS", region: "V" },
  { name: "Ragay", province: "CAS", region: "V" },
  { name: "Sagñay", province: "CAS", region: "V" },
  { name: "San Fernando", province: "CAS", region: "V" },
  { name: "San Jose", province: "CAS", region: "V" },
  { name: "Sipocot", province: "CAS", region: "V" },
  { name: "Siruma", province: "CAS", region: "V" },
  { name: "Tigaon", province: "CAS", region: "V" },
  { name: "Tinambac", province: "CAS", region: "V" },
  { name: "Bagamanoc", province: "CAT", region: "V" },
  { name: "Baras", province: "CAT", region: "V" },
  { name: "Bato", province: "CAT", region: "V" },
  { name: "Caramoran", province: "CAT", region: "V" },
  { name: "Gigmoto", province: "CAT", region: "V" },
  { name: "Pandan", province: "CAT", region: "V" },
  { name: "Panganiban", province: "CAT", region: "V" },
  { name: "San Andres", province: "CAT", region: "V" },
  { name: "San Miguel", province: "CAT", region: "V" },
  { name: "Viga", province: "CAT", region: "V" },
  { name: "Virac", province: "CAT", region: "V" },
  { name: "Aroroy", province: "MAS", region: "V" },
  { name: "Baleno", province: "MAS", region: "V" },
  { name: "Balud", province: "MAS", region: "V" },
  { name: "Batuan", province: "MAS", region: "V" },
  { name: "Cataingan", province: "MAS", region: "V" },
  { name: "Cawayan", province: "MAS", region: "V" },
  { name: "Claveria", province: "MAS", region: "V" },
  { name: "Dimasalang", province: "MAS", region: "V" },
  { name: "Esperanza", province: "MAS", region: "V" },
  { name: "Mandaon", province: "MAS", region: "V" },
  { name: "Masbate", province: "MAS", city: true, region: "V" },
  { name: "Milagros", province: "MAS", region: "V" },
  { name: "Mobo", province: "MAS", region: "V" },
  { name: "Monreal", province: "MAS", region: "V" },
  { name: "Palanas", province: "MAS", region: "V" },
  { name: "Pio V. Corpuz", province: "MAS", region: "V" },
  { name: "Placer", province: "MAS", region: "V" },
  { name: "San Fernando", province: "MAS", region: "V" },
  { name: "San Jacinto", province: "MAS", region: "V" },
  { name: "San Pascual", province: "MAS", region: "V" },
  { name: "Uson", province: "MAS", region: "V" },
  { name: "Barcelona", province: "SOR", region: "V" },
  { name: "Bulan", province: "SOR", region: "V" },
  { name: "Bulusan", province: "SOR", region: "V" },
  { name: "Casiguran", province: "SOR", region: "V" },
  { name: "Castilla", province: "SOR", region: "V" },
  { name: "Donsol", province: "SOR", region: "V" },
  { name: "Gubat", province: "SOR", region: "V" },
  { name: "Irosin", province: "SOR", region: "V" },
  { name: "Juban", province: "SOR", region: "V" },
  { name: "Magallanes", province: "SOR", region: "V" },
  { name: "Matnog", province: "SOR", region: "V" },
  { name: "Pilar", province: "SOR", region: "V" },
  { name: "Prieto Diaz", province: "SOR", region: "V" },
  { name: "Santa Magdalena", province: "SOR", region: "V" },
  { name: "Sorsogon", province: "SOR", city: true, region: "V" },
  { name: "Altavas", province: "AKL", region: "VI" },
  { name: "Balete", province: "AKL", region: "VI" },
  { name: "Banga", province: "AKL", region: "VI" },
  { name: "Batan", province: "AKL", region: "VI" },
  { name: "Buruanga", province: "AKL", region: "VI" },
  { name: "Ibajay", province: "AKL", region: "VI" },
  { name: "Kalibo", province: "AKL", region: "VI" },
  { name: "Lezo", province: "AKL", region: "VI" },
  { name: "Libacao", province: "AKL", region: "VI" },
  { name: "Madalag", province: "AKL", region: "VI" },
  { name: "Makato", province: "AKL", region: "VI" },
  { name: "Malay", province: "AKL", region: "VI" },
  { name: "Malinao", province: "AKL", region: "VI" },
  { name: "Nabas", province: "AKL", region: "VI" },
  { name: "New Washington", province: "AKL", region: "VI" },
  { name: "Numancia", province: "AKL", region: "VI" },
  { name: "Tangalan", province: "AKL", region: "VI" },
  { name: "Anini-y", province: "ANT", region: "VI" },
  { name: "Barbaza", province: "ANT", region: "VI" },
  { name: "Belison", province: "ANT", region: "VI" },
  { name: "Bugasong", province: "ANT", region: "VI" },
  { name: "Caluya", province: "ANT", region: "VI" },
  { name: "Culasi", province: "ANT", region: "VI" },
  { name: "Hamtic", province: "ANT", region: "VI" },
  { name: "Laua-an", province: "ANT", region: "VI" },
  { name: "Libertad", province: "ANT", region: "VI" },
  { name: "Pandan", province: "ANT", region: "VI" },
  { name: "Patnongon", province: "ANT", region: "VI" },
  { name: "San Jose", province: "ANT", region: "VI" },
  { name: "San Remigio", province: "ANT", region: "VI" },
  { name: "Sebaste", province: "ANT", region: "VI" },
  { name: "Sibalom", province: "ANT", region: "VI" },
  { name: "Tibiao", province: "ANT", region: "VI" },
  { name: "Tobias Fornier", province: "ANT", region: "VI" },
  { name: "Valderrama", province: "ANT", region: "VI" },
  { name: "Cuartero", province: "CAP", region: "VI" },
  { name: "Dao", province: "CAP", region: "VI" },
  { name: "Dumalag", province: "CAP", region: "VI" },
  { name: "Dumarao", province: "CAP", region: "VI" },
  { name: "Ivisan", province: "CAP", region: "VI" },
  { name: "Jamindan", province: "CAP", region: "VI" },
  { name: "Maayon", province: "CAP", region: "VI" },
  { name: "Mambusao", province: "CAP", region: "VI" },
  { name: "Panay", province: "CAP", region: "VI" },
  { name: "Panitan", province: "CAP", region: "VI" },
  { name: "Pilar", province: "CAP", region: "VI" },
  { name: "Pontevedra", province: "CAP", region: "VI" },
  { name: "President Roxas", province: "CAP", region: "VI" },
  { name: "Roxas", province: "CAP", city: true, region: "VI" },
  { name: "Sapian", province: "CAP", region: "VI" },
  { name: "Sigma", province: "CAP", region: "VI" },
  { name: "Tapaz", province: "CAP", region: "VI" },
  { name: "Buenavista", province: "GUI", region: "VI" },
  { name: "Jordan", province: "GUI", region: "VI" },
  { name: "Nueva Valencia", province: "GUI", region: "VI" },
  { name: "San Lorenzo", province: "GUI", region: "VI" },
  { name: "Sibunag", province: "GUI", region: "VI" },
  { name: "Ajuy", province: "ILI", region: "VI" },
  { name: "Alimodian", province: "ILI", region: "VI" },
  { name: "Anilao", province: "ILI", region: "VI" },
  { name: "Badiangan", province: "ILI", region: "VI" },
  { name: "Balasan", province: "ILI", region: "VI" },
  { name: "Banate", province: "ILI", region: "VI" },
  { name: "Barotac Nuevo", province: "ILI", region: "VI" },
  { name: "Barotac Viejo", province: "ILI", region: "VI" },
  { name: "Batad", province: "ILI", region: "VI" },
  { name: "Bingawan", province: "ILI", region: "VI" },
  { name: "Cabatuan", province: "ILI", region: "VI" },
  { name: "Calinog", province: "ILI", region: "VI" },
  { name: "Carles", province: "ILI", region: "VI" },
  { name: "Concepcion", province: "ILI", region: "VI" },
  { name: "Dingle", province: "ILI", region: "VI" },
  { name: "Dueñas", province: "ILI", region: "VI" },
  { name: "Dumangas", province: "ILI", region: "VI" },
  { name: "Estancia", province: "ILI", region: "VI" },
  { name: "Guimbal", province: "ILI", region: "VI" },
  { name: "Igbaras", province: "ILI", region: "VI" },
  { name: "Iloilo", province: "ILI", city: true, region: "VI" },
  { name: "Janiuay", province: "ILI", region: "VI" },
  { name: "Lambunao", province: "ILI", region: "VI" },
  { name: "Leganes", province: "ILI", region: "VI" },
  { name: "Lemery", province: "ILI", region: "VI" },
  { name: "Leon", province: "ILI", region: "VI" },
  { name: "Maasin", province: "ILI", region: "VI" },
  { name: "Miagao", province: "ILI", region: "VI" },
  { name: "Mina", province: "ILI", region: "VI" },
  { name: "New Lucena", province: "ILI", region: "VI" },
  { name: "Oton", province: "ILI", region: "VI" },
  { name: "Passi", province: "ILI", city: true, region: "VI" },
  { name: "Pavia", province: "ILI", region: "VI" },
  { name: "Pototan", province: "ILI", region: "VI" },
  { name: "San Dionisio", province: "ILI", region: "VI" },
  { name: "San Enrique", province: "ILI", region: "VI" },
  { name: "San Joaquin", province: "ILI", region: "VI" },
  { name: "San Miguel", province: "ILI", region: "VI" },
  { name: "San Rafael", province: "ILI", region: "VI" },
  { name: "Santa Barbara", province: "ILI", region: "VI" },
  { name: "Sara", province: "ILI", region: "VI" },
  { name: "Tigbauan", province: "ILI", region: "VI" },
  { name: "Tubungan", province: "ILI", region: "VI" },
  { name: "Zarraga", province: "ILI", region: "VI" },
  { name: "Bacolod", province: "NEC", city: true, region: "VI" },
  { name: "Bago", province: "NEC", city: true, region: "VI" },
  { name: "Binalbagan", province: "NEC", region: "VI" },
  { name: "Cadiz", province: "NEC", city: true, region: "VI" },
  { name: "Calatrava", province: "NEC", region: "VI" },
  { name: "Candoni", province: "NEC", region: "VI" },
  { name: "Cauayan", province: "NEC", region: "VI" },
  { name: "Enrique B. Magalona", province: "NEC", region: "VI" },
  { name: "Escalante", province: "NEC", city: true, region: "VI" },
  { name: "Himamaylan", province: "NEC", city: true, region: "VI" },
  { name: "Hinigaran", province: "NEC", region: "VI" },
  { name: "Hinoba-an", province: "NEC", region: "VI" },
  { name: "Ilog", province: "NEC", region: "VI" },
  { name: "Isabela", province: "NEC", region: "VI" },
  { name: "Kabankalan", province: "NEC", city: true, region: "VI" },
  { name: "La Carlota", province: "NEC", city: true, region: "VI" },
  { name: "La Castellana", province: "NEC", region: "VI" },
  { name: "Manapla", province: "NEC", region: "VI" },
  { name: "Moises Padilla", province: "NEC", region: "VI" },
  { name: "Murcia", province: "NEC", region: "VI" },
  { name: "Pontevedra", province: "NEC", region: "VI" },
  { name: "Pulupandan", province: "NEC", region: "VI" },
  { name: "Sagay", province: "NEC", city: true, region: "VI" },
  { name: "Salvador Benedicto", province: "NEC", region: "VI" },
  { name: "San Carlos", province: "NEC", city: true, region: "VI" },
  { name: "San Enrique", province: "NEC", region: "VI" },
  { name: "Silay", province: "NEC", city: true, region: "VI" },
  { name: "Sipalay", province: "NEC", city: true, region: "VI" },
  { name: "Talisay", province: "NEC", city: true, region: "VI" },
  { name: "Toboso", province: "NEC", region: "VI" },
  { name: "Valladolid", province: "NEC", region: "VI" },
  { name: "Victorias", province: "NEC", city: true, region: "VI" },
  { name: "Alburquerque", province: "BOH", region: "VII" },
  { name: "Alicia", province: "BOH", region: "VII" },
  { name: "Anda", province: "BOH", region: "VII" },
  { name: "Antequera", province: "BOH", region: "VII" },
  { name: "Baclayon", province: "BOH", region: "VII" },
  { name: "Balilihan", province: "BOH", region: "VII" },
  { name: "Batuan", province: "BOH", region: "VII" },
  { name: "Bien Unido", province: "BOH", region: "VII" },
  { name: "Bilar", province: "BOH", region: "VII" },
  { name: "Buenavista", province: "BOH", region: "VII" },
  { name: "Calape", province: "BOH", region: "VII" },
  { name: "Candijay", province: "BOH", region: "VII" },
  { name: "Carmen", province: "BOH", region: "VII" },
  { name: "Catigbian", province: "BOH", region: "VII" },
  { name: "Clarin", province: "BOH", region: "VII" },
  { name: "Corella", province: "BOH", region: "VII" },
  { name: "Cortes", province: "BOH", region: "VII" },
  { name: "Dagohoy", province: "BOH", region: "VII" },
  { name: "Danao", province: "BOH", region: "VII" },
  { name: "Dauis", province: "BOH", region: "VII" },
  { name: "Dimiao", province: "BOH", region: "VII" },
  { name: "Duero", province: "BOH", region: "VII" },
  { name: "Garcia Hernandez", province: "BOH", region: "VII" },
  { name: "Getafe", province: "BOH", region: "VII" },
  { name: "Guindulman", province: "BOH", region: "VII" },
  { name: "Inabanga", province: "BOH", region: "VII" },
  { name: "Jagna", province: "BOH", region: "VII" },
  { name: "Lila", province: "BOH", region: "VII" },
  { name: "Loay", province: "BOH", region: "VII" },
  { name: "Loboc", province: "BOH", region: "VII" },
  { name: "Loon", province: "BOH", region: "VII" },
  { name: "Mabini", province: "BOH", region: "VII" },
  { name: "Maribojoc", province: "BOH", region: "VII" },
  { name: "Panglao", province: "BOH", region: "VII" },
  { name: "Pilar", province: "BOH", region: "VII" },
  { name: "President Carlos P. Garcia", province: "BOH", region: "VII" },
  { name: "Sagbayan", province: "BOH", region: "VII" },
  { name: "San Isidro", province: "BOH", region: "VII" },
  { name: "San Miguel", province: "BOH", region: "VII" },
  { name: "Sevilla", province: "BOH", region: "VII" },
  { name: "Sierra Bullones", province: "BOH", region: "VII" },
  { name: "Sikatuna", province: "BOH", region: "VII" },
  { name: "Tagbilaran", province: "BOH", city: true, region: "VII" },
  { name: "Talibon", province: "BOH", region: "VII" },
  { name: "Trinidad", province: "BOH", region: "VII" },
  { name: "Tubigon", province: "BOH", region: "VII" },
  { name: "Ubay", province: "BOH", region: "VII" },
  { name: "Valencia", province: "BOH", region: "VII" },
  { name: "Alcantara", province: "CEB", region: "VII" },
  { name: "Alcoy", province: "CEB", region: "VII" },
  { name: "Alegria", province: "CEB", region: "VII" },
  { name: "Aloguinsan", province: "CEB", region: "VII" },
  { name: "Argao", province: "CEB", region: "VII" },
  { name: "Asturias", province: "CEB", region: "VII" },
  { name: "Badian", province: "CEB", region: "VII" },
  { name: "Balamban", province: "CEB", region: "VII" },
  { name: "Bantayan", province: "CEB", region: "VII" },
  { name: "Barili", province: "CEB", region: "VII" },
  { name: "Bogo", province: "CEB", city: true, region: "VII" },
  { name: "Boljoon", province: "CEB", region: "VII" },
  { name: "Borbon", province: "CEB", region: "VII" },
  { name: "Carcar", province: "CEB", city: true, region: "VII" },
  { name: "Carmen", province: "CEB", region: "VII" },
  { name: "Catmon", province: "CEB", region: "VII" },
  { name: "Cebu", province: "CEB", city: true, region: "VII" },
  { name: "Compostela", province: "CEB", region: "VII" },
  { name: "Consolacion", province: "CEB", region: "VII" },
  { name: "Cordoba", province: "CEB", region: "VII" },
  { name: "Daanbantayan", province: "CEB", region: "VII" },
  { name: "Dalaguete", province: "CEB", region: "VII" },
  { name: "Danao", province: "CEB", city: true, region: "VII" },
  { name: "Dumanjug", province: "CEB", region: "VII" },
  { name: "Ginatilan", province: "CEB", region: "VII" },
  { name: "Lapu-Lapu", province: "CEB", city: true, region: "VII" },
  { name: "Liloan", province: "CEB", region: "VII" },
  { name: "Madridejos", province: "CEB", region: "VII" },
  { name: "Malabuyoc", province: "CEB", region: "VII" },
  { name: "Mandaue", province: "CEB", city: true, region: "VII" },
  { name: "Medellin", province: "CEB", region: "VII" },
  { name: "Minglanilla", province: "CEB", region: "VII" },
  { name: "Moalboal", province: "CEB", region: "VII" },
  { name: "Naga", province: "CEB", city: true, region: "VII" },
  { name: "Oslob", province: "CEB", region: "VII" },
  { name: "Pilar", province: "CEB", region: "VII" },
  { name: "Pinamungajan", province: "CEB", region: "VII" },
  { name: "Poro", province: "CEB", region: "VII" },
  { name: "Ronda", province: "CEB", region: "VII" },
  { name: "Samboan", province: "CEB", region: "VII" },
  { name: "San Fernando", province: "CEB", region: "VII" },
  { name: "San Francisco", province: "CEB", region: "VII" },
  { name: "San Remigio", province: "CEB", region: "VII" },
  { name: "Santa Fe", province: "CEB", region: "VII" },
  { name: "Santander", province: "CEB", region: "VII" },
  { name: "Sibonga", province: "CEB", region: "VII" },
  { name: "Sogod", province: "CEB", region: "VII" },
  { name: "Tabogon", province: "CEB", region: "VII" },
  { name: "Tabuelan", province: "CEB", region: "VII" },
  { name: "Talisay", province: "CEB", city: true, region: "VII" },
  { name: "Toledo", province: "CEB", city: true, region: "VII" },
  { name: "Tuburan", province: "CEB", region: "VII" },
  { name: "Tudela", province: "CEB", region: "VII" },
  { name: "Amlan", province: "NER", region: "VII" },
  { name: "Ayungon", province: "NER", region: "VII" },
  { name: "Bacong", province: "NER", region: "VII" },
  { name: "Bais", province: "NER", city: true, region: "VII" },
  { name: "Basay", province: "NER", region: "VII" },
  { name: "Bayawan", province: "NER", city: true, region: "VII" },
  { name: "Bindoy", province: "NER", region: "VII" },
  { name: "Canlaon", province: "NER", city: true, region: "VII" },
  { name: "Dauin", province: "NER", region: "VII" },
  { name: "Dumaguete", province: "NER", city: true, region: "VII" },
  { name: "Guihulngan", province: "NER", city: true, region: "VII" },
  { name: "Jimalalud", province: "NER", region: "VII" },
  { name: "La Libertad", province: "NER", region: "VII" },
  { name: "Mabinay", province: "NER", region: "VII" },
  { name: "Manjuyod", province: "NER", region: "VII" },
  { name: "Pamplona", province: "NER", region: "VII" },
  { name: "San Jose", province: "NER", region: "VII" },
  { name: "Santa Catalina", province: "NER", region: "VII" },
  { name: "Siaton", province: "NER", region: "VII" },
  { name: "Sibulan", province: "NER", region: "VII" },
  { name: "Tanjay", province: "NER", city: true, region: "VII" },
  { name: "Tayasan", province: "NER", region: "VII" },
  { name: "Valencia", province: "NER", region: "VII" },
  { name: "Vallehermoso", province: "NER", region: "VII" },
  { name: "Zamboanguita", province: "NER", region: "VII" },
  { name: "Enrique Villanueva", province: "SIG", region: "VII" },
  { name: "Larena", province: "SIG", region: "VII" },
  { name: "Lazi", province: "SIG", region: "VII" },
  { name: "Maria", province: "SIG", region: "VII" },
  { name: "San Juan", province: "SIG", region: "VII" },
  { name: "Siquijor", province: "SIG", region: "VII" },
  { name: "Almeria", province: "BIL", region: "VIII" },
  { name: "Biliran", province: "BIL", region: "VIII" },
  { name: "Cabucgayan", province: "BIL", region: "VIII" },
  { name: "Caibiran", province: "BIL", region: "VIII" },
  { name: "Culaba", province: "BIL", region: "VIII" },
  { name: "Kawayan", province: "BIL", region: "VIII" },
  { name: "Maripipi", province: "BIL", region: "VIII" },
  { name: "Naval", province: "BIL", region: "VIII" },
  { name: "Arteche", province: "EAS", region: "VIII" },
  { name: "Balangiga", province: "EAS", region: "VIII" },
  { name: "Balangkayan", province: "EAS", region: "VIII" },
  { name: "Borongan", province: "EAS", city: true, region: "VIII" },
  { name: "Can-avid", province: "EAS", region: "VIII" },
  { name: "Dolores", province: "EAS", region: "VIII" },
  { name: "General MacArthur", province: "EAS", region: "VIII" },
  { name: "Giporlos", province: "EAS", region: "VIII" },
  { name: "Guiuan", province: "EAS", region: "VIII" },
  { name: "Hernani", province: "EAS", region: "VIII" },
  { name: "Jipapad", province: "EAS", region: "VIII" },
  { name: "Lawaan", province: "EAS", region: "VIII" },
  { name: "Llorente", province: "EAS", region: "VIII" },
  { name: "Maslog", province: "EAS", region: "VIII" },
  { name: "Maydolong", province: "EAS", region: "VIII" },
  { name: "Mercedes", province: "EAS", region: "VIII" },
  { name: "Oras", province: "EAS", region: "VIII" },
  { name: "Quinapondan", province: "EAS", region: "VIII" },
  { name: "Salcedo", province: "EAS", region: "VIII" },
  { name: "San Julian", province: "EAS", region: "VIII" },
  { name: "San Policarpo", province: "EAS", region: "VIII" },
  { name: "Sulat", province: "EAS", region: "VIII" },
  { name: "Taft", province: "EAS", region: "VIII" },
  { name: "Abuyog", province: "LEY", region: "VIII" },
  { name: "Alangalang", province: "LEY", region: "VIII" },
  { name: "Albuera", province: "LEY", region: "VIII" },
  { name: "Babatngon", province: "LEY", region: "VIII" },
  { name: "Barugo", province: "LEY", region: "VIII" },
  { name: "Bato", province: "LEY", region: "VIII" },
  { name: "Baybay", province: "LEY", city: true, region: "VIII" },
  { name: "Burauen", province: "LEY", region: "VIII" },
  { name: "Calubian", province: "LEY", region: "VIII" },
  { name: "Capoocan", province: "LEY", region: "VIII" },
  { name: "Carigara", province: "LEY", region: "VIII" },
  { name: "Dagami", province: "LEY", region: "VIII" },
  { name: "Dulag", province: "LEY", region: "VIII" },
  { name: "Hilongos", province: "LEY", region: "VIII" },
  { name: "Hindang", province: "LEY", region: "VIII" },
  { name: "Inopacan", province: "LEY", region: "VIII" },
  { name: "Isabel", province: "LEY", region: "VIII" },
  { name: "Jaro", province: "LEY", region: "VIII" },
  { name: "Javier", province: "LEY", region: "VIII" },
  { name: "Julita", province: "LEY", region: "VIII" },
  { name: "Kananga", province: "LEY", region: "VIII" },
  { name: "La Paz", province: "LEY", region: "VIII" },
  { name: "Leyte", province: "LEY", region: "VIII" },
  { name: "MacArthur", province: "LEY", region: "VIII" },
  { name: "Mahaplag", province: "LEY", region: "VIII" },
  { name: "Matag-ob", province: "LEY", region: "VIII" },
  { name: "Matalom", province: "LEY", region: "VIII" },
  { name: "Mayorga", province: "LEY", region: "VIII" },
  { name: "Merida", province: "LEY", region: "VIII" },
  { name: "Ormoc", province: "LEY", city: true, region: "VIII" },
  { name: "Palo", province: "LEY", region: "VIII" },
  { name: "Palompon", province: "LEY", region: "VIII" },
  { name: "Pastrana", province: "LEY", region: "VIII" },
  { name: "San Isidro", province: "LEY", region: "VIII" },
  { name: "San Miguel", province: "LEY", region: "VIII" },
  { name: "Santa Fe", province: "LEY", region: "VIII" },
  { name: "Tabango", province: "LEY", region: "VIII" },
  { name: "Tabontabon", province: "LEY", region: "VIII" },
  { name: "Tacloban", province: "LEY", city: true, region: "VIII" },
  { name: "Tanauan", province: "LEY", region: "VIII" },
  { name: "Tolosa", province: "LEY", region: "VIII" },
  { name: "Tunga", province: "LEY", region: "VIII" },
  { name: "Villaba", province: "LEY", region: "VIII" },
  { name: "Allen", province: "NSA", region: "VIII" },
  { name: "Biri", province: "NSA", region: "VIII" },
  { name: "Bobon", province: "NSA", region: "VIII" },
  { name: "Capul", province: "NSA", region: "VIII" },
  { name: "Catarman", province: "NSA", region: "VIII" },
  { name: "Catubig", province: "NSA", region: "VIII" },
  { name: "Gamay", province: "NSA", region: "VIII" },
  { name: "Laoang", province: "NSA", region: "VIII" },
  { name: "Lapinig", province: "NSA", region: "VIII" },
  { name: "Las Navas", province: "NSA", region: "VIII" },
  { name: "Lavezares", province: "NSA", region: "VIII" },
  { name: "Lope de Vega", province: "NSA", region: "VIII" },
  { name: "Mapanas", province: "NSA", region: "VIII" },
  { name: "Mondragon", province: "NSA", region: "VIII" },
  { name: "Palapag", province: "NSA", region: "VIII" },
  { name: "Pambujan", province: "NSA", region: "VIII" },
  { name: "Rosario", province: "NSA", region: "VIII" },
  { name: "San Antonio", province: "NSA", region: "VIII" },
  { name: "San Isidro", province: "NSA", region: "VIII" },
  { name: "San Jose", province: "NSA", region: "VIII" },
  { name: "San Roque", province: "NSA", region: "VIII" },
  { name: "San Vicente", province: "NSA", region: "VIII" },
  { name: "Silvino Lobos", province: "NSA", region: "VIII" },
  { name: "Victoria", province: "NSA", region: "VIII" },
  { name: "Almagro", province: "WSA", region: "VIII" },
  { name: "Basey", province: "WSA", region: "VIII" },
  { name: "Calbayog", province: "WSA", city: true, region: "VIII" },
  { name: "Calbiga", province: "WSA", region: "VIII" },
  { name: "Catbalogan", province: "WSA", city: true, region: "VIII" },
  { name: "Daram", province: "WSA", region: "VIII" },
  { name: "Gandara", province: "WSA", region: "VIII" },
  { name: "Hinabangan", province: "WSA", region: "VIII" },
  { name: "Jiabong", province: "WSA", region: "VIII" },
  { name: "Marabut", province: "WSA", region: "VIII" },
  { name: "Matuguinao", province: "WSA", region: "VIII" },
  { name: "Motiong", province: "WSA", region: "VIII" },
  { name: "Pagsanghan", province: "WSA", region: "VIII" },
  { name: "Paranas", province: "WSA", region: "VIII" },
  { name: "Pinabacdao", province: "WSA", region: "VIII" },
  { name: "San Jorge", province: "WSA", region: "VIII" },
  { name: "San Jose de Buan", province: "WSA", region: "VIII" },
  { name: "San Sebastian", province: "WSA", region: "VIII" },
  { name: "Santa Margarita", province: "WSA", region: "VIII" },
  { name: "Santa Rita", province: "WSA", region: "VIII" },
  { name: "Santo Niño", province: "WSA", region: "VIII" },
  { name: "Tagapul-an", province: "WSA", region: "VIII" },
  { name: "Talalora", province: "WSA", region: "VIII" },
  { name: "Tarangnan", province: "WSA", region: "VIII" },
  { name: "Villareal", province: "WSA", region: "VIII" },
  { name: "Zumarraga", province: "WSA", region: "VIII" },
  { name: "Anahawan", province: "SLE", region: "VIII" },
  { name: "Bontoc", province: "SLE", region: "VIII" },
  { name: "Hinunangan", province: "SLE", region: "VIII" },
  { name: "Hinundayan", province: "SLE", region: "VIII" },
  { name: "Libagon", province: "SLE", region: "VIII" },
  { name: "Liloan", province: "SLE", region: "VIII" },
  { name: "Limasawa", province: "SLE", region: "VIII" },
  { name: "Maasin", province: "SLE", city: true, region: "VIII" },
  { name: "Macrohon", province: "SLE", region: "VIII" },
  { name: "Malitbog", province: "SLE", region: "VIII" },
  { name: "Padre Burgos", province: "SLE", region: "VIII" },
  { name: "Pintuyan", province: "SLE", region: "VIII" },
  { name: "Saint Bernard", province: "SLE", region: "VIII" },
  { name: "San Francisco", province: "SLE", region: "VIII" },
  { name: "San Juan", province: "SLE", region: "VIII" },
  { name: "San Ricardo", province: "SLE", region: "VIII" },
  { name: "Silago", province: "SLE", region: "VIII" },
  { name: "Sogod", province: "SLE", region: "VIII" },
  { name: "Tomas Oppus", province: "SLE", region: "VIII" },
  { name: "Baliguian", province: "ZAN", region: "IX" },
  { name: "Dapitan", province: "ZAN", city: true, region: "IX" },
  { name: "Dipolog", province: "ZAN", city: true, region: "IX" },
  { name: "Godod", province: "ZAN", region: "IX" },
  { name: "Gutalac", province: "ZAN", region: "IX" },
  { name: "Jose Dalman", province: "ZAN", region: "IX" },
  { name: "Kalawit", province: "ZAN", region: "IX" },
  { name: "Katipunan", province: "ZAN", region: "IX" },
  { name: "La Libertad", province: "ZAN", region: "IX" },
  { name: "Labason", province: "ZAN", region: "IX" },
  { name: "Leon B. Postigo", province: "ZAN", region: "IX" },
  { name: "Liloy", province: "ZAN", region: "IX" },
  { name: "Manukan", province: "ZAN", region: "IX" },
  { name: "Mutia", province: "ZAN", region: "IX" },
  { name: "Piñan", province: "ZAN", region: "IX" },
  { name: "Polanco", province: "ZAN", region: "IX" },
  { name: "President Manuel A. Roxas", province: "ZAN", region: "IX" },
  { name: "Rizal", province: "ZAN", region: "IX" },
  { name: "Salug", province: "ZAN", region: "IX" },
  { name: "Sergio Osmeña Sr.", province: "ZAN", region: "IX" },
  { name: "Siayan", province: "ZAN", region: "IX" },
  { name: "Sibuco", province: "ZAN", region: "IX" },
  { name: "Sibutad", province: "ZAN", region: "IX" },
  { name: "Sindangan", province: "ZAN", region: "IX" },
  { name: "Siocon", province: "ZAN", region: "IX" },
  { name: "Sirawai", province: "ZAN", region: "IX" },
  { name: "Tampilisan", province: "ZAN", region: "IX" },
  { name: "Aurora", province: "ZAS", region: "IX" },
  { name: "Bayog", province: "ZAS", region: "IX" },
  { name: "Dimataling", province: "ZAS", region: "IX" },
  { name: "Dinas", province: "ZAS", region: "IX" },
  { name: "Dumalinao", province: "ZAS", region: "IX" },
  { name: "Dumingag", province: "ZAS", region: "IX" },
  { name: "Guipos", province: "ZAS", region: "IX" },
  { name: "Josefina", province: "ZAS", region: "IX" },
  { name: "Kumalarang", province: "ZAS", region: "IX" },
  { name: "Labangan", province: "ZAS", region: "IX" },
  { name: "Lakewood", province: "ZAS", region: "IX" },
  { name: "Lapuyan", province: "ZAS", region: "IX" },
  { name: "Mahayag", province: "ZAS", region: "IX" },
  { name: "Margosatubig", province: "ZAS", region: "IX" },
  { name: "Midsalip", province: "ZAS", region: "IX" },
  { name: "Molave", province: "ZAS", region: "IX" },
  { name: "Pagadian", province: "ZAS", city: true, region: "IX" },
  { name: "Pitogo", province: "ZAS", region: "IX" },
  { name: "Ramon Magsaysay", province: "ZAS", region: "IX" },
  { name: "San Miguel", province: "ZAS", region: "IX" },
  { name: "San Pablo", province: "ZAS", region: "IX" },
  { name: "Sominot", province: "ZAS", region: "IX" },
  { name: "Tabina", province: "ZAS", region: "IX" },
  { name: "Tambulig", province: "ZAS", region: "IX" },
  { name: "Tigbao", province: "ZAS", region: "IX" },
  { name: "Tukuran", province: "ZAS", region: "IX" },
  { name: "Vincenzo A. Sagun", province: "ZAS", region: "IX" },
  { name: "Zamboanga", province: "ZAS", city: true, region: "IX" },
  { name: "Alicia", province: "ZSI", region: "IX" },
  { name: "Buug", province: "ZSI", region: "IX" },
  { name: "Diplahan", province: "ZSI", region: "IX" },
  { name: "Imelda", province: "ZSI", region: "IX" },
  { name: "Ipil", province: "ZSI", region: "IX" },
  { name: "Kabasalan", province: "ZSI", region: "IX" },
  { name: "Mabuhay", province: "ZSI", region: "IX" },
  { name: "Malangas", province: "ZSI", region: "IX" },
  { name: "Naga", province: "ZSI", region: "IX" },
  { name: "Olutanga", province: "ZSI", region: "IX" },
  { name: "Payao", province: "ZSI", region: "IX" },
  { name: "Roseller Lim", province: "ZSI", region: "IX" },
  { name: "Siay", province: "ZSI", region: "IX" },
  { name: "Talusan", province: "ZSI", region: "IX" },
  { name: "Titay", province: "ZSI", region: "IX" },
  { name: "Tungawan", province: "ZSI", region: "IX" },
  { name: "Baungon", province: "BUK", region: "X" },
  { name: "Cabanglasan", province: "BUK", region: "X" },
  { name: "Damulog", province: "BUK", region: "X" },
  { name: "Dangcagan", province: "BUK", region: "X" },
  { name: "Don Carlos", province: "BUK", region: "X" },
  { name: "Impasugong", province: "BUK", region: "X" },
  { name: "Kadingilan", province: "BUK", region: "X" },
  { name: "Kalilangan", province: "BUK", region: "X" },
  { name: "Kibawe", province: "BUK", region: "X" },
  { name: "Kitaotao", province: "BUK", region: "X" },
  { name: "Lantapan", province: "BUK", region: "X" },
  { name: "Libona", province: "BUK", region: "X" },
  { name: "Malaybalay", province: "BUK", city: true, region: "X" },
  { name: "Malitbog", province: "BUK", region: "X" },
  { name: "Manolo Fortich", province: "BUK", region: "X" },
  { name: "Maramag", province: "BUK", region: "X" },
  { name: "Pangantucan", province: "BUK", region: "X" },
  { name: "Quezon", province: "BUK", region: "X" },
  { name: "San Fernando", province: "BUK", region: "X" },
  { name: "Sumilao", province: "BUK", region: "X" },
  { name: "Talakag", province: "BUK", region: "X" },
  { name: "Valencia", province: "BUK", city: true, region: "X" },
  { name: "Catarman", province: "CAM", region: "X" },
  { name: "Guinsiliban", province: "CAM", region: "X" },
  { name: "Mahinog", province: "CAM", region: "X" },
  { name: "Mambajao", province: "CAM", region: "X" },
  { name: "Sagay", province: "CAM", region: "X" },
  { name: "Bacolod", province: "LAN", region: "X" },
  { name: "Baloi", province: "LAN", region: "X" },
  { name: "Baroy", province: "LAN", region: "X" },
  { name: "Iligan", province: "LAN", city: true, region: "X" },
  { name: "Kapatagan", province: "LAN", region: "X" },
  { name: "Kauswagan", province: "LAN", region: "X" },
  { name: "Kolambugan", province: "LAN", region: "X" },
  { name: "Lala", province: "LAN", region: "X" },
  { name: "Linamon", province: "LAN", region: "X" },
  { name: "Magsaysay", province: "LAN", region: "X" },
  { name: "Maigo", province: "LAN", region: "X" },
  { name: "Matungao", province: "LAN", region: "X" },
  { name: "Munai", province: "LAN", region: "X" },
  { name: "Nunungan", province: "LAN", region: "X" },
  { name: "Pantao Ragat", province: "LAN", region: "X" },
  { name: "Pantar", province: "LAN", region: "X" },
  { name: "Poona Piagapo", province: "LAN", region: "X" },
  { name: "Salvador", province: "LAN", region: "X" },
  { name: "Sapad", province: "LAN", region: "X" },
  { name: "Sultan Naga Dimaporo", province: "LAN", region: "X" },
  { name: "Tagoloan", province: "LAN", region: "X" },
  { name: "Tangcal", province: "LAN", region: "X" },
  { name: "Tubod", province: "LAN", region: "X" },
  { name: "Aloran", province: "MSC", region: "X" },
  { name: "Baliangao", province: "MSC", region: "X" },
  { name: "Bonifacio", province: "MSC", region: "X" },
  { name: "Calamba", province: "MSC", region: "X" },
  { name: "Clarin", province: "MSC", region: "X" },
  { name: "Concepcion", province: "MSC", region: "X" },
  { name: "Don Victoriano Chiongbian", province: "MSC", region: "X" },
  { name: "Jimenez", province: "MSC", region: "X" },
  { name: "Lopez Jaena", province: "MSC", region: "X" },
  { name: "Oroquieta", province: "MSC", city: true, region: "X" },
  { name: "Ozamiz", province: "MSC", city: true, region: "X" },
  { name: "Panaon", province: "MSC", region: "X" },
  { name: "Plaridel", province: "MSC", region: "X" },
  { name: "Sapang Dalaga", province: "MSC", region: "X" },
  { name: "Sinacaban", province: "MSC", region: "X" },
  { name: "Tangub", province: "MSC", city: true, region: "X" },
  { name: "Tudela", province: "MSC", region: "X" },
  { name: "Alubijid", province: "MSR", region: "X" },
  { name: "Balingasag", province: "MSR", region: "X" },
  { name: "Balingoan", province: "MSR", region: "X" },
  { name: "Binuangan", province: "MSR", region: "X" },
  { name: "Cagayan de Oro", province: "MSR", city: true, region: "X" },
  { name: "Claveria", province: "MSR", region: "X" },
  { name: "El Salvador", province: "MSR", city: true, region: "X" },
  { name: "Gingoog", province: "MSR", city: true, region: "X" },
  { name: "Gitagum", province: "MSR", region: "X" },
  { name: "Initao", province: "MSR", region: "X" },
  { name: "Jasaan", province: "MSR", region: "X" },
  { name: "Kinoguitan", province: "MSR", region: "X" },
  { name: "Lagonglong", province: "MSR", region: "X" },
  { name: "Laguindingan", province: "MSR", region: "X" },
  { name: "Libertad", province: "MSR", region: "X" },
  { name: "Lugait", province: "MSR", region: "X" },
  { name: "Magsaysay", province: "MSR", region: "X" },
  { name: "Manticao", province: "MSR", region: "X" },
  { name: "Medina", province: "MSR", region: "X" },
  { name: "Naawan", province: "MSR", region: "X" },
  { name: "Opol", province: "MSR", region: "X" },
  { name: "Salay", province: "MSR", region: "X" },
  { name: "Sugbongcogon", province: "MSR", region: "X" },
  { name: "Tagoloan", province: "MSR", region: "X" },
  { name: "Talisayan", province: "MSR", region: "X" },
  { name: "Villanueva", province: "MSR", region: "X" },
  { name: "Compostela", province: "COM", region: "XI" },
  { name: "Laak", province: "COM", region: "XI" },
  { name: "Mabini", province: "COM", region: "XI" },
  { name: "Maco", province: "COM", region: "XI" },
  { name: "Maragusan", province: "COM", region: "XI" },
  { name: "Mawab", province: "COM", region: "XI" },
  { name: "Monkayo", province: "COM", region: "XI" },
  { name: "Montevista", province: "COM", region: "XI" },
  { name: "Nabunturan", province: "COM", region: "XI" },
  { name: "New Bataan", province: "COM", region: "XI" },
  { name: "Pantukan", province: "COM", region: "XI" },
  { name: "Asuncion", province: "DAV", region: "XI" },
  { name: "Braulio E. Dujali", province: "DAV", region: "XI" },
  { name: "Carmen", province: "DAV", region: "XI" },
  { name: "Kapalong", province: "DAV", region: "XI" },
  { name: "New Corella", province: "DAV", region: "XI" },
  { name: "Panabo", province: "DAV", city: true, region: "XI" },
  { name: "Samal", province: "DAV", city: true, region: "XI" },
  { name: "San Isidro", province: "DAV", region: "XI" },
  { name: "Santo Tomas", province: "DAV", region: "XI" },
  { name: "Tagum", province: "DAV", city: true, region: "XI" },
  { name: "Talaingod", province: "DAV", region: "XI" },
  { name: "Bansalan", province: "DAS", region: "XI" },
  { name: "Davao", province: "DAS", city: true, region: "XI" },
  { name: "Digos", province: "DAS", city: true, region: "XI" },
  { name: "Hagonoy", province: "DAS", region: "XI" },
  { name: "Kiblawan", province: "DAS", region: "XI" },
  { name: "Magsaysay", province: "DAS", region: "XI" },
  { name: "Malalag", province: "DAS", region: "XI" },
  { name: "Matanao", province: "DAS", region: "XI" },
  { name: "Padada", province: "DAS", region: "XI" },
  { name: "Santa Cruz", province: "DAS", region: "XI" },
  { name: "Sulop", province: "DAS", region: "XI" },
  { name: "Don Marcelino", province: "DAC", region: "XI" },
  { name: "Jose Abad Santos", province: "DAC", region: "XI" },
  { name: "Malita", province: "DAC", region: "XI" },
  { name: "Santa Maria", province: "DAC", region: "XI" },
  { name: "Sarangani", province: "DAC", region: "XI" },
  { name: "Baganga", province: "DAO", region: "XI" },
  { name: "Banaybanay", province: "DAO", region: "XI" },
  { name: "Boston", province: "DAO", region: "XI" },
  { name: "Caraga", province: "DAO", region: "XI" },
  { name: "Cateel", province: "DAO", region: "XI" },
  { name: "Governor Generoso", province: "DAO", region: "XI" },
  { name: "Lupon", province: "DAO", region: "XI" },
  { name: "Manay", province: "DAO", region: "XI" },
  { name: "Mati", province: "DAO", city: true, region: "XI" },
  { name: "San Isidro", province: "DAO", region: "XI" },
  { name: "Tarragona", province: "DAO", region: "XI" },
  { name: "Alamada", province: "NCO", region: "XII" },
  { name: "Aleosan", province: "NCO", region: "XII" },
  { name: "Antipas", province: "NCO", region: "XII" },
  { name: "Arakan", province: "NCO", region: "XII" },
  { name: "Banisilan", province: "NCO", region: "XII" },
  { name: "Carmen", province: "NCO", region: "XII" },
  { name: "Kabacan", province: "NCO", region: "XII" },
  { name: "Kidapawan", province: "NCO", city: true, region: "XII" },
  { name: "Libungan", province: "NCO", region: "XII" },
  { name: "M'lang", province: "NCO", region: "XII" },
  { name: "Magpet", province: "NCO", region: "XII" },
  { name: "Makilala", province: "NCO", region: "XII" },
  { name: "Matalam", province: "NCO", region: "XII" },
  { name: "Midsayap", province: "NCO", region: "XII" },
  { name: "Pigcawayan", province: "NCO", region: "XII" },
  { name: "Pikit", province: "NCO", region: "XII" },
  { name: "President Roxas", province: "NCO", region: "XII" },
  { name: "Tulunan", province: "NCO", region: "XII" },
  { name: "Alabel", province: "SAR", region: "XII" },
  { name: "Glan", province: "SAR", region: "XII" },
  { name: "Kiamba", province: "SAR", region: "XII" },
  { name: "Maasim", province: "SAR", region: "XII" },
  { name: "Maitum", province: "SAR", region: "XII" },
  { name: "Malapatan", province: "SAR", region: "XII" },
  { name: "Malungon", province: "SAR", region: "XII" },
  { name: "Banga", province: "SCO", region: "XII" },
  { name: "General Santos", province: "SCO", city: true, region: "XII" },
  { name: "Koronadal", province: "SCO", city: true, region: "XII" },
  { name: "Lake Sebu", province: "SCO", region: "XII" },
  { name: "Norala", province: "SCO", region: "XII" },
  { name: "Polomolok", province: "SCO", region: "XII" },
  { name: "Santo Niño", province: "SCO", region: "XII" },
  { name: "Surallah", province: "SCO", region: "XII" },
  { name: "T'boli", province: "SCO", region: "XII" },
  { name: "Tampakan", province: "SCO", region: "XII" },
  { name: "Tantangan", province: "SCO", region: "XII" },
  { name: "Tupi", province: "SCO", region: "XII" },
  { name: "Bagumbayan", province: "SUK", region: "XII" },
  { name: "Columbio", province: "SUK", region: "XII" },
  { name: "Esperanza", province: "SUK", region: "XII" },
  { name: "Isulan", province: "SUK", region: "XII" },
  { name: "Kalamansig", province: "SUK", region: "XII" },
  { name: "Lambayong", province: "SUK", region: "XII" },
  { name: "Lebak", province: "SUK", region: "XII" },
  { name: "Lutayan", province: "SUK", region: "XII" },
  { name: "Palimbang", province: "SUK", region: "XII" },
  { name: "President Quirino", province: "SUK", region: "XII" },
  { name: "Senator Ninoy Aquino", province: "SUK", region: "XII" },
  { name: "Tacurong", province: "SUK", city: true, region: "XII" },
  { name: "Buenavista", province: "AGN", region: "XIII" },
  { name: "Butuan", province: "AGN", city: true, region: "XIII" },
  { name: "Cabadbaran", province: "AGN", city: true, region: "XIII" },
  { name: "Carmen", province: "AGN", region: "XIII" },
  { name: "Jabonga", province: "AGN", region: "XIII" },
  { name: "Kitcharao", province: "AGN", region: "XIII" },
  { name: "Las Nieves", province: "AGN", region: "XIII" },
  { name: "Magallanes", province: "AGN", region: "XIII" },
  { name: "Nasipit", province: "AGN", region: "XIII" },
  { name: "Remedios T. Romualdez", province: "AGN", region: "XIII" },
  { name: "Santiago", province: "AGN", region: "XIII" },
  { name: "Tubay", province: "AGN", region: "XIII" },
  { name: "Bayugan", province: "AGS", city: true, region: "XIII" },
  { name: "Bunawan", province: "AGS", region: "XIII" },
  { name: "Esperanza", province: "AGS", region: "XIII" },
  { name: "La Paz", province: "AGS", region: "XIII" },
  { name: "Loreto", province: "AGS", region: "XIII" },
  { name: "Prosperidad", province: "AGS", region: "XIII" },
  { name: "Rosario", province: "AGS", region: "XIII" },
  { name: "San Francisco", province: "AGS", region: "XIII" },
  { name: "San Luis", province: "AGS", region: "XIII" },
  { name: "Santa Josefa", province: "AGS", region: "XIII" },
  { name: "Sibagat", province: "AGS", region: "XIII" },
  { name: "Talacogon", province: "AGS", region: "XIII" },
  { name: "Trento", province: "AGS", region: "XIII" },
  { name: "Veruela", province: "AGS", region: "XIII" },
  { name: "Basilisa", province: "DIN", region: "XIII" },
  { name: "Cagdianao", province: "DIN", region: "XIII" },
  { name: "Dinagat", province: "DIN", region: "XIII" },
  { name: "Libjo", province: "DIN", region: "XIII" },
  { name: "Loreto", province: "DIN", region: "XIII" },
  { name: "San Jose", province: "DIN", region: "XIII" },
  { name: "Tubajon", province: "DIN", region: "XIII" },
  { name: "Alegria", province: "SUN", region: "XIII" },
  { name: "Bacuag", province: "SUN", region: "XIII" },
  { name: "Burgos", province: "SUN", region: "XIII" },
  { name: "Claver", province: "SUN", region: "XIII" },
  { name: "Dapa", province: "SUN", region: "XIII" },
  { name: "Del Carmen", province: "SUN", region: "XIII" },
  { name: "General Luna", province: "SUN", region: "XIII" },
  { name: "Gigaquit", province: "SUN", region: "XIII" },
  { name: "Mainit", province: "SUN", region: "XIII" },
  { name: "Malimono", province: "SUN", region: "XIII" },
  { name: "Pilar", province: "SUN", region: "XIII" },
  { name: "Placer", province: "SUN", region: "XIII" },
  { name: "San Benito", province: "SUN", region: "XIII" },
  { name: "San Francisco", province: "SUN", region: "XIII" },
  { name: "San Isidro", province: "SUN", region: "XIII" },
  { name: "Santa Monica", province: "SUN", region: "XIII" },
  { name: "Sison", province: "SUN", region: "XIII" },
  { name: "Socorro", province: "SUN", region: "XIII" },
  { name: "Surigao", province: "SUN", city: true, region: "XIII" },
  { name: "Tagana-an", province: "SUN", region: "XIII" },
  { name: "Tubod", province: "SUN", region: "XIII" },
  { name: "Barobo", province: "SUR", region: "XIII" },
  { name: "Bayabas", province: "SUR", region: "XIII" },
  { name: "Bislig", province: "SUR", city: true, region: "XIII" },
  { name: "Cagwait", province: "SUR", region: "XIII" },
  { name: "Cantilan", province: "SUR", region: "XIII" },
  { name: "Carmen", province: "SUR", region: "XIII" },
  { name: "Carrascal", province: "SUR", region: "XIII" },
  { name: "Cortes", province: "SUR", region: "XIII" },
  { name: "Hinatuan", province: "SUR", region: "XIII" },
  { name: "Lanuza", province: "SUR", region: "XIII" },
  { name: "Lianga", province: "SUR", region: "XIII" },
  { name: "Lingig", province: "SUR", region: "XIII" },
  { name: "Madrid", province: "SUR", region: "XIII" },
  { name: "Marihatag", province: "SUR", region: "XIII" },
  { name: "San Agustin", province: "SUR", region: "XIII" },
  { name: "San Miguel", province: "SUR", region: "XIII" },
  { name: "Tagbina", province: "SUR", region: "XIII" },
  { name: "Tago", province: "SUR", region: "XIII" },
  { name: "Tandag", province: "SUR", city: true, region: "XIII" },
  { name: "Akbar", province: "BAS", region: "ARMM" },
  { name: "Al-Barka", province: "BAS", region: "ARMM" },
  { name: "Hadji Mohammad Ajul", province: "BAS", region: "ARMM" },
  { name: "Hadji Muhtamad", province: "BAS", region: "ARMM" },
  { name: "Isabela", province: "BAS", city: true, region: "ARMM" },
  { name: "Lamitan", province: "BAS", city: true, region: "ARMM" },
  { name: "Lantawan", province: "BAS", region: "ARMM" },
  { name: "Maluso", province: "BAS", region: "ARMM" },
  { name: "Sumisip", province: "BAS", region: "ARMM" },
  { name: "Tabuan-Lasa", province: "BAS", region: "ARMM" },
  { name: "Tipo-Tipo", province: "BAS", region: "ARMM" },
  { name: "Tuburan", province: "BAS", region: "ARMM" },
  { name: "Ungkaya Pukan", province: "BAS", region: "ARMM" },
  { name: "Bacolod-Kalawi", province: "LAS", region: "ARMM" },
  { name: "Balabagan", province: "LAS", region: "ARMM" },
  { name: "Balindong", province: "LAS", region: "ARMM" },
  { name: "Bayang", province: "LAS", region: "ARMM" },
  { name: "Binidayan", province: "LAS", region: "ARMM" },
  { name: "Buadiposo-Buntong", province: "LAS", region: "ARMM" },
  { name: "Bubong", province: "LAS", region: "ARMM" },
  { name: "Bumbaran", province: "LAS", region: "ARMM" },
  { name: "Butig", province: "LAS", region: "ARMM" },
  { name: "Calanogas", province: "LAS", region: "ARMM" },
  { name: "Ditsaan-Ramain", province: "LAS", region: "ARMM" },
  { name: "Ganassi", province: "LAS", region: "ARMM" },
  { name: "Kapai", province: "LAS", region: "ARMM" },
  { name: "Kapatagan", province: "LAS", region: "ARMM" },
  { name: "Lumba-Bayabao", province: "LAS", region: "ARMM" },
  { name: "Lumbaca-Unayan", province: "LAS", region: "ARMM" },
  { name: "Lumbatan", province: "LAS", region: "ARMM" },
  { name: "Lumbayanague", province: "LAS", region: "ARMM" },
  { name: "Madalum", province: "LAS", region: "ARMM" },
  { name: "Madamba", province: "LAS", region: "ARMM" },
  { name: "Maguing", province: "LAS", region: "ARMM" },
  { name: "Malabang", province: "LAS", region: "ARMM" },
  { name: "Marantao", province: "LAS", region: "ARMM" },
  { name: "Marawi", province: "LAS", city: true, region: "ARMM" },
  { name: "Marogong", province: "LAS", region: "ARMM" },
  { name: "Masiu", province: "LAS", region: "ARMM" },
  { name: "Mulondo", province: "LAS", region: "ARMM" },
  { name: "Pagayawan", province: "LAS", region: "ARMM" },
  { name: "Piagapo", province: "LAS", region: "ARMM" },
  { name: "Poona Bayabao", province: "LAS", region: "ARMM" },
  { name: "Pualas", province: "LAS", region: "ARMM" },
  { name: "Saguiaran", province: "LAS", region: "ARMM" },
  { name: "Sultan Dumalondong", province: "LAS", region: "ARMM" },
  { name: "Picong", province: "LAS", region: "ARMM" },
  { name: "Tagoloan II", province: "LAS", region: "ARMM" },
  { name: "Tamparan", province: "LAS", region: "ARMM" },
  { name: "Taraka", province: "LAS", region: "ARMM" },
  { name: "Tubaran", province: "LAS", region: "ARMM" },
  { name: "Tugaya", province: "LAS", region: "ARMM" },
  { name: "Wao", province: "LAS", region: "ARMM" },
  { name: "Ampatuan", province: "MAG", region: "ARMM" },
  { name: "Barira", province: "MAG", region: "ARMM" },
  { name: "Buldon", province: "MAG", region: "ARMM" },
  { name: "Buluan", province: "MAG", region: "ARMM" },
  { name: "Cotabato", province: "MAG", city: true, region: "ARMM" },
  { name: "Datu Abdullah Sangki", province: "MAG", region: "ARMM" },
  { name: "Datu Anggal Midtimbang", province: "MAG", region: "ARMM" },
  { name: "Datu Blah T. Sinsuat", province: "MAG", region: "ARMM" },
  { name: "Datu Hoffer Ampatuan", province: "MAG", region: "ARMM" },
  { name: "Datu Montawal", province: "MAG", region: "ARMM" },
  { name: "Datu Odin Sinsuat", province: "MAG", region: "ARMM" },
  { name: "Datu Paglas", province: "MAG", region: "ARMM" },
  { name: "Datu Piang", province: "MAG", region: "ARMM" },
  { name: "Datu Salibo", province: "MAG", region: "ARMM" },
  { name: "Datu Saudi-Ampatuan", province: "MAG", region: "ARMM" },
  { name: "Datu Unsay", province: "MAG", region: "ARMM" },
  { name: "General Salipada K. Pendatun", province: "MAG", region: "ARMM" },
  { name: "Guindulungan", province: "MAG", region: "ARMM" },
  { name: "Kabuntalan", province: "MAG", region: "ARMM" },
  { name: "Mamasapano", province: "MAG", region: "ARMM" },
  { name: "Mangudadatu", province: "MAG", region: "ARMM" },
  { name: "Matanog", province: "MAG", region: "ARMM" },
  { name: "Northern Kabuntalan", province: "MAG", region: "ARMM" },
  { name: "Pagalungan", province: "MAG", region: "ARMM" },
  { name: "Paglat", province: "MAG", region: "ARMM" },
  { name: "Pandag", province: "MAG", region: "ARMM" },
  { name: "Parang", province: "MAG", region: "ARMM" },
  { name: "Rajah Buayan", province: "MAG", region: "ARMM" },
  { name: "Shariff Aguak", province: "MAG", region: "ARMM" },
  { name: "Shariff Saydona Mustapha", province: "MAG", region: "ARMM" },
  { name: "South Upi", province: "MAG", region: "ARMM" },
  { name: "Sultan Kudarat", province: "MAG", region: "ARMM" },
  { name: "Sultan Mastura", province: "MAG", region: "ARMM" },
  { name: "Sultan sa Barongis", province: "MAG", region: "ARMM" },
  { name: "Sultan Sumagka", province: "MAG", region: "ARMM" },
  { name: "Talayan", province: "MAG", region: "ARMM" },
  { name: "Upi", province: "MAG", region: "ARMM" },
  { name: "Banguingui", province: "SLU", region: "ARMM" },
  { name: "Hadji Panglima Tahil", province: "SLU", region: "ARMM" },
  { name: "Indanan", province: "SLU", region: "ARMM" },
  { name: "Jolo", province: "SLU", region: "ARMM" },
  { name: "Kalingalan Caluang", province: "SLU", region: "ARMM" },
  { name: "Lugus", province: "SLU", region: "ARMM" },
  { name: "Luuk", province: "SLU", region: "ARMM" },
  { name: "Maimbung", province: "SLU", region: "ARMM" },
  { name: "Old Panamao", province: "SLU", region: "ARMM" },
  { name: "Omar", province: "SLU", region: "ARMM" },
  { name: "Pandami", province: "SLU", region: "ARMM" },
  { name: "Panglima Estino", province: "SLU", region: "ARMM" },
  { name: "Pangutaran", province: "SLU", region: "ARMM" },
  { name: "Parang", province: "SLU", region: "ARMM" },
  { name: "Pata", province: "SLU", region: "ARMM" },
  { name: "Patikul", province: "SLU", region: "ARMM" },
  { name: "Siasi", province: "SLU", region: "ARMM" },
  { name: "Talipao", province: "SLU", region: "ARMM" },
  { name: "Tapul", province: "SLU", region: "ARMM" },
  { name: "Bongao", province: "TAW", region: "ARMM" },
  { name: "Languyan", province: "TAW", region: "ARMM" },
  { name: "Mapun", province: "TAW", region: "ARMM" },
  { name: "Panglima Sugala", province: "TAW", region: "ARMM" },
  { name: "Sapa-Sapa", province: "TAW", region: "ARMM" },
  { name: "Sibutu", province: "TAW", region: "ARMM" },
  { name: "Simunul", province: "TAW", region: "ARMM" },
  { name: "Sitangkai", province: "TAW", region: "ARMM" },
  { name: "South Ubian", province: "TAW", region: "ARMM" },
  { name: "Tandubas", province: "TAW", region: "ARMM" },
  { name: "Turtle Islands", province: "TAW", region: "ARMM" },
];
export { cities, provinces, regions };
